### ISSUE TITLE
GET requests are working, POST requests are not (Updated/See Comments)

### ISSUE THREAD

**Issue by cwcoomes** [timheuer/alexa-skills-dotnet#103]
I am having a weird issue regarding LaunchRequests. For some reason, when I say "Alexa, open/start Skill ABC", the JSON output is null for the LaunchRequest. IntentRequests work just fine ("Alexa, ask Skill ABC <utterance>" returns what it's supposed to with no problems. 

Please see my code below: 

`using Alexa.NET.Request;
using Alexa.NET.Response;
using Alexa.NET.Request.Type;
using System.Data.SqlClient;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs.Host;
using System.Data;
using Alexa.NET;
using System;

namespace SkillABC
{

    public static class SkillABCFunction
    {
        [FunctionName("SkillABC")]
        public static SkillResponse Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)][FromBody]SkillRequest incomingRequest, TraceWriter log)
        {
            PlainTextOutputSpeech outputSpeech = new PlainTextOutputSpeech();
            string intentName = (incomingRequest.Request as IntentRequest).Intent.Name;
            var request = incomingRequest.Request as IntentRequest;

            switch (incomingRequest.Request)
            {
                case LaunchRequest launch: // This returns null.

                    outputSpeech.Text = "Hello. My name is Skill ABC. How are you today";
                    SkillResponse skillResponse = new SkillResponse();
                    skillResponse.Version = "1.0";
                    skillResponse.Response = new ResponseBody();
                    skillResponse.Response.OutputSpeech = outputSpeech;
                    skillResponse.Response.ShouldEndSession = true;
                    return skillResponse;

                case IntentRequest intent:
                    if (intentName.Equals("RollTheDice")) // This is a dialog that works perfectly.
                    {
                        return RollDiceHandler(incomingRequest);
                    }
                  default:
                      //...
                }
              }
         }
    }
} `

A couple of things I have tried so far:
1. Using the built-in helper to generate the SkillResponse object
2. Sending the output of incomingRequest.GetRequestType().ToString() to as my SkillResponse to an IntentRequest, which... only plays a sound when invoked by Alexa.

**Comment by stoiveyp** [comment]
Hi @cwcoomes - if I'm reading the code correctly it will currently only work for intents.

In your second line `(incomingRequest.Request as IntentRequest)` will produce a null output for LaunchRequest objects, or anything other than an intent. This means the `.Intent.Name` part of the statement will be against a null object and generate a NullReferenceException

I'd move that line to inside the case statement for IntentRequest and remove the subsequent line, as you already have an intentRequest being generated with the statement `case IntentRequest intent`

Hopefully this should move the skill forward. Please let me know if it doesn't, or if you have any other questions.

**Comment by cwcoomes** [comment]
This was working fine until this past weekend. I am not sure what's wrong, but for some reason the following is returning NULL for POST requests... I have contacted Azure about this but I'm just making sure this is not a problem with my code?

`using Alexa.NET.Request;
using Alexa.NET.Response;
using Alexa.NET.Request.Type;
using System.Data.SqlClient;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs.Host;
using System.Data;
using Alexa.NET;
using System;


namespace MyFunction
{

    public static class MyFunction
    {
        
        static readonly string azureConnection = "---Connection String---";
        static SqlConnection connection;
        static string welcomeMessage = "Welcome.";

        [FunctionName("FuncCall")]
        public static SkillResponse Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)][FromBody]SkillRequest incomingRequest, TraceWriter log)
        {


            SkillResponse skillResponseForBuilder;
            PlainTextOutputSpeech outputSpeech = new PlainTextOutputSpeech();
 
            switch (incomingRequest.Request)
            {
                case LaunchRequest launch:

                    outputSpeech.Text = welcomeMessage;
                    SkillResponse skillResponse = new SkillResponse();
                    skillResponse.Version = "1.0";
                    skillResponse.SessionAttributes = null;
                    skillResponse.Response = new ResponseBody();
                    skillResponse.Response.OutputSpeech = outputSpeech;
                    skillResponse.Response.ShouldEndSession = false;
                    return skillResponse;
                    

                case IntentRequest intent:
                    string intentName = intent.Intent.Name;
                    if (intentName.Equals("RollTheDice"))
                    {
                        return RollDiceHandler(incomingRequest);
                    }
                    else if (intentName.Equals("CheckIn")) 
                    {
                        return CheckInHandler(incomingRequest);
                    }
                    else
                    {
                        DataTable funcdt = new DataTable();
                        using (connection = new SqlConnection(azureConnection))
                        using (
                            SqlCommand cmd = new SqlCommand("SPCallFunction", connection)
                            {
                                CommandType = CommandType.StoredProcedure
                            })

                        {
                            connection.Open();
                            cmd.Parameters.Add(new SqlParameter("@IntentKey", intentName));
                            SqlDataReader funcdr = cmd.ExecuteReader();
                            funcdt.Load(funcdr);
                            if (funcdt.Rows.Count != 0)
                            {
                                outputSpeech.Text = funcdt.Rows[0]["IntentValue"].ToString();
                                connection.Close();
                            }
                            else
                            {
                                outputSpeech.Text = incomingRequest.GetRequestType().ToString();
                                connection.Close();
                            }

                        }
                    }

                    skillResponseForBuilder = ResponseBuilder.Tell(outputSpeech);
                    return skillResponseForBuilder;


                default:
                    outputSpeech.Text = "Error.";
                    skillResponseForBuilder = ResponseBuilder.Tell(outputSpeech.Text);
                    return skillResponseForBuilder;
            }
        }

        // Test dialog handler
        public static SkillResponse RollDiceHandler(SkillRequest req)
        {
            SkillResponse skillResponse = new SkillResponse();
            PlainTextOutputSpeech outputSpeech = new PlainTextOutputSpeech();
            var request = req.Request as IntentRequest;
            if (request.DialogState == DialogState.Started)
            {
                return ResponseBuilder.DialogDelegate(req.Session, request.Intent);
            }
            else if (request.DialogState != DialogState.Completed)
            {
                return ResponseBuilder.DialogDelegate(req.Session);
            }
            else
            {
                skillResponse.Response = new ResponseBody();
                skillResponse.Response.ShouldEndSession = false;
                if (request.Intent.Slots["DiceType"].Value != null)
                {
                    var numSides = request.Intent.Slots["DiceType"].Value;
                    var rollResults = new Random().Next(Math.Max(1, Convert.ToInt32(numSides) - 1)) + 1;
                    outputSpeech.Text = "I rolled a " + numSides + " sided die and got a " + rollResults;
                    skillResponse.Response.OutputSpeech = outputSpeech;
                    skillResponse.Response.ShouldEndSession = true;
                    skillResponse.Version = "1.0";
                    
                }
                else
                {
                    outputSpeech.Text = "Hello.";
                    skillResponse.Response.OutputSpeech = outputSpeech;
                    skillResponse.Version = "1.0";
                    if (request.Intent.Slots["DiceType"].Value != null)
                    {
                        var numSides = request.Intent.Slots["DiceType"].Value;
                        var rollResults = new Random().Next(Math.Max(1, Convert.ToInt32(numSides) - 1)) + 1;
                        outputSpeech.Text = "I rolled a " + numSides + " sided die and got a " + rollResults;
                        skillResponse.Response.OutputSpeech = outputSpeech;
                        skillResponse.Response.ShouldEndSession = true;
                        skillResponse.Version = "1.0";
                    }

                }
                return skillResponse;
            }
        }


        public static SkillResponse CheckInHandler(SkillRequest req)
        {
            SkillResponse skillResponse = new SkillResponse();
            PlainTextOutputSpeech outputSpeech = new PlainTextOutputSpeech();
            var request = req.Request as IntentRequest;
            if (request.DialogState == DialogState.Started)
            {
                return ResponseBuilder.DialogDelegate(req.Session, request.Intent);
            }
            else if (request.DialogState != DialogState.Completed)
            {
                return ResponseBuilder.DialogDelegate(req.Session);
            }
            else
            {
                skillResponse.Response = new ResponseBody();
                skillResponse.Response.ShouldEndSession = false;
                if (request.Intent.Slots["TechnicianName"].Value != null && request.Intent.Slots["TicketNumber"].Value != null)
                {
                    var techName = request.Intent.Slots["TechnicianName"].Value;
                    var ticketNumber = request.Intent.Slots["TicketNumber"].Value;
                    if (request.Intent.Slots["TechnicianCompany"].Value != null)
                    {
                        var techCompany = request.Intent.Slots["TechnicianCompany"].Value;
                        
                    }                    

                    outputSpeech.Text = "Thank you.";
                        
                    skillResponse.Response.OutputSpeech = outputSpeech;
                    skillResponse.Response.ShouldEndSession = true;
                    skillResponse.Version = "1.0";
                }
                return skillResponse;
            }
        } 
    }   
}`
