### ISSUE TITLE
Not able to use SSML

### ISSUE THREAD

**Issue by JJLucena** [timheuer/alexa-skills-dotnet#104]
I am trying to develop an alexa skill and i have to play short audios or/and text so the best way to do it as far as I am concerned is using ssml but at the time of sending ssml info to alexa it gives me an error.

         public SkillResponse FunctionHandler(SkillRequest input, ILambdaContext context)
        `{
            var soundLink = new Alexa.NET.Response.SsmlOutputSpeech();
            bool soundResponse = false;
            IOutputSpeech innerResponse = null;

            SkillResponse response = new SkillResponse();
            response.Response = new ResponseBody();
            response.Response.ShouldEndSession = false;

            var allResources = GetInfo();
            var info = allResources.FirstOrDefault();
            var requestType = input.GetRequestType();

            if (requestType == typeof(LaunchRequest))
            {
                innerResponse = new PlainTextOutputSpeech();
                (innerResponse as PlainTextOutputSpeech).Text = "¿Que sonido quieres?";
            }
            else if (requestType == typeof(IntentRequest))
            {
                var intentRequest = (IntentRequest)input.Request;
                switch (intentRequest.Intent.Name)
                {
                    case "soundRequest":
                        innerResponse = new PlainTextOutputSpeech();
                        var instrumentRequest = intentRequest.Intent.Slots["instrument"].Value;
                        var noteRequest = intentRequest.Intent.Slots["note"].Value;
                        if (instrumentRequest == null)
                        {
                            (innerResponse as PlainTextOutputSpeech).Text = "¿Que instrumento quieres?";
                        } else {
                            if (instrumentRequest == "piano")
                            {
                                if (noteRequest == null)
                                {
                                    (innerResponse as PlainTextOutputSpeech).Text = "¿Que nota quieres?";
                                } else {
                                    if (noteRequest == "la")
                                    {
                                        soundResponse = true;
                                        soundLink.Ssml = "<audio src=\"https://s3.eu-west-1.amazonaws.com/afinadorcromaticosounds/piano/A_piano.mp3\" />";
                                    }
                                }
                        }
                        break;
                    default:
                        innerResponse = new PlainTextOutputSpeech();
                        (innerResponse as PlainTextOutputSpeech).Text = info.HelpReprompt;
                        break;
                }
            }

            var finalResponse = Alexa.NET.ResponseBuilder.Tell(soundLink);
            if (!soundResponse)
            {
                response.Response.OutputSpeech = innerResponse;
                response.Version = "2.1";
                finalResponse = response;
            }
            return finalResponse;
        }`

My problem then is that when i send the sound intent it detects the ssml and the link(it is what the JSON output shows) but it returns an error and closes the skill.

**Comment by stoiveyp** [comment]
Hi @JJLucena - your SSML has to start with a \<speak\> tag, otherwise it's not valid SSML.

Alternatively you can use the Speech object in Alexa.NET.Response.SSML to take away some of the markup maintenance.

```csharp
using Alexa.NET.Response.Ssml;
...
soundLink.Ssml = new Speech(new Audio("https://s3.eu-west-1.amazonaws.com/afinadorcromaticosounds/piano/A_piano.mp3")).ToXml();
```

**Comment by JJLucena** [comment]
Thanks for the help, now everything works fine.
