### ISSUE TITLE
AudioPlayerResponse

### ISSUE THREAD

**Issue by JJLucena** [timheuer/alexa-skills-dotnet#105]
Hello,
I am using AudioPlayer and Response.Directives to play audio with alexa but it returns an empty response.
I do not know if I have to add some property to the response or change how the response is returned. 

`sound.Stream.Url = ("https://s3.eu-west-1.amazonaws.com/afinadorcromaticosounds/guitar/A_guit.mp3");
response.Response.Directives.Add(new AudioPlayerPlayDirective() {
                    PlayBehavior = PlayBehavior.ReplaceAll,
                    AudioItem = sound
                });
                response.Response.ShouldEndSession = false;
 return response;`

Thanks in advance for the help.

**Comment by stoiveyp** [comment]
Afternoon @JJLucena - two things I notice that are worth checking.

1. You need to have a token set for the stream object, it's a required field for the interface
2. ShouldEndSession should be set to true, otherwise it won't play the audio (it will pause it waiting for a user response)

Let me know how that goes?

**Comment by JJLucena** [comment]
Thanks for the response but I still get the same problem, It seems like it is detecting the response as an empty one, is there any way to specify that the response is an AudioItem?

**Comment by DanBusc** [comment]
try this way @JJLucena ... videoplayer is commented out, you don't need it
`
...
directive = GetPlayerDirective(input, song);
if (directive != null)
{
       response.Response.Directives.Add(directive);
}
....
 private IDirective GetPlayerDirective(SkillRequest input, Song song)
        {
            /* if (HasDisplay(input))
                return getVideoPlayerDirective(input, song);
            else
                if (CanPlaySounds(input))*/
                return getAudioplayerDirective(input, song);
            /*else
                return null;*/
        }
private IDirective getAudioplayerDirective(SkillRequest input, Song song)
        {
            var dir = new AudioPlayerPlayDirective();
            var item = new AudioItem();
            var stream = new AudioItemStream()
            {
                Token = getToken(input),
                Url = song.StreamMP3,
                OffsetInMilliseconds = 0
            };

            item.Stream = stream;
            dir.AudioItem = item;

            var sources = new AudioItemSources();
            var source = new AudioItemSource("https://s3-eu-west-1.amazonaws.com/YOURIMAGE.PNG");
            sources.Sources.Add(source);

            var arts = new AudioItemSources();
            var art = new AudioItemSource(song.AlbumImage);
            arts.Sources.Add(art);
            
            item.Metadata = new AudioItemMetadata() { Title = song.Name, Subtitle = song.SubTitle, Art = arts, BackgroundImage = sources };

            return dir;
        }`

Class Song:
`public class Song
    {
        public enum StreamType
        {
            MP3,
            MP4
        }
        public int ID { get; set; }
        public string Name { get; set; }
        public string StreamMP3 { get; set; }
        public string StreamMP4 { get; set; }
        public string SubTitle { get; set; }
        public string AlbumImage { get; set; }

        public Song(int id, string name, string streamURL, StreamType streamtype)
        {
            ID = id;
            Name = name;
            switch (streamtype)
            {
                case StreamType.MP3:
                    StreamMP3 = streamURL;
                    break;
                case StreamType.MP4:
                    StreamMP4 = streamURL;
                    break;
                default:
                    break;
            }
        }
        public Song(int id, string name, string streammp3, string streammp4,  string subtitle, string image)
        {
            this.ID = id;
            this.Name = name;
            this.StreamMP3 = streammp3;
            this.StreamMP4 = streammp4;
            this.SubTitle = subtitle;
            this.AlbumImage = image;

        }
    }`

Let me know if it helps

**Comment by JJLucena** [comment]
That is perfect, it helped a lot.
I am going to close the issue due to it is alredy solved.
