### ISSUE TITLE
ProgressiveResponse in async await context

### ISSUE THREAD

**Issue by andreasassetti** [timheuer/alexa-skills-dotnet#108]
Hi, I have a small issue. I probably can not handle the "async await" pattern correctly.

I'm creating two different tasks to handle the long operation and at the same time inform the user that the system is working on it.

In both case, with the simulator and with the physical device, I receive first of all only on "work in progress" response and immediately after the "completion response".

Below the extract of my code.... 

My Intent manager.
   ```
 public class Fake
    {
        private CancellationTokenSource _cancellationTokenSource;
        private SkillRequest _skillRequest;
        private ProgressiveResponse _progressiveResponse;


        public Fake(SkillRequest skillRequest)
        {
            _skillRequest = skillRequest;
            _progressiveResponse = new ProgressiveResponse(skillRequest);
        }


        public async Task<SkillResponse> Handle()
        {
            _cancellationTokenSource = new CancellationTokenSource();

            var tasks = new List<Task<bool>>
            {
                Timer1(),
                Timer()
            };

            await Task.WhenAny(tasks);

            return Fluent.Speak("Done").AndShouldEndSession(true).Response;
        }

        private async Task<bool> Timer1()
        {
            await Task.Delay(TimeSpan.FromSeconds(45));

            _cancellationTokenSource.Cancel();

            return true;
        }

        private async Task<bool> Timer()
        {
            while (true)
            {
                await Task.Delay(TimeSpan.FromSeconds(15));

                if (_cancellationTokenSource.IsCancellationRequested)
                    return true;

                if (_progressiveResponse.CanSend())
                    await _progressiveResponse.SendSpeech("I'm working on it");
            }
        }
    }
```

This is the Function

```
 public class Function
    {
        public async Task<SkillResponse> FunctionHandler(SkillRequest skillRequest, ILambdaContext lambdaContext)
        {
            var fake = new Fake(skillRequest);

            return await fake.Handle();
        }
    }
```

Apparently during debugging in VS the asynchronicity is respected.

Any suggestions?

Thanks, regards
Andrea

**Comment by stoiveyp** [comment]
Hi. Sorry for the delay - Friday was really busy for me.

To help with async/await I've written out the flow below:

- Start Timer 1 45 second delay
- Start Timer 15 second delay
- Wait until either timer or timer1 completes
- Timer 15 second timer completes
- Progressive Response sends "working on it"
- Handle sends "I'm done"
- Timer1 may or may not complete, depending on when task is terminated.

In this instance you know you have a minimum of 15 seconds to wait before you can respond correctly, so by all means start timer and timer1 (you want them completing ASAP), but then send the progressive response to give feedback to the user that their command has been understood. 

So you'll end up with (I changed the progressive response slightly to show that the user now knows it's okay that they're waiting)

```csharp
 var tasks = new List<Task<bool>>{ Timer1(), Timer() };

if (_progressiveResponse.CanSend())
    await _progressiveResponse.SendSpeech("I'm working on it, I'll just be a few more seconds");

await Task.WhenAny(tasks);
```

Alternatively, if you know one task will always complete faster than the other:

```
var timerTask = Timer();
var timer1Task = Timer1();

if (_progressiveResponse.CanSend())
    await _progressiveResponse.SendSpeech("I'm working on it, I'll just be a few more seconds");

await timerTask;

if (_progressiveResponse.CanSend())
    await _progressiveResponse.SendSpeech("It's going to be worth the wait, just a little longer");

await timer1Task
```

If you know your task _has_ to take a long time, I'd recommend taking advantage of the fact that you can send up to five progressive response commands to ensure your user is being regularly communicated with - as long periods of silence will make them feel that the skill has failed or stopped.

```csharp
 var tasks = new List<Task<bool>>{ Timer1(), Timer() };

if (_progressiveResponse.CanSend())
{
    var progress1 = _progressiveResponse.SendSpeech("I'm working on it, I'll just be a few more seconds");
    await Task.WhenAll(progress1, Task.Delay(7));
    var progress2 = _pressiveResponse.SendSpeech("Almost there, totally worth the wait");
    await Task.WhenAll(progress2, Task.Delay(7));
}

await Task.WhenAny(tasks);
```
If you don't know how long the real task will take then you could do a loop that does the same thing, and keeps sending them until either there's been 5 progressive responses or the task has completed.

Also - WhenAny means that only one of the two tasks needs to complete - is that correct? If both need to complete then use `.WhenAll`. If not then the cancellationtoken probably needs to be used after one of them has completed to cancel the other.

A long explanation but hopefully it helps explain things and progressive response isn't something a lot of people use - but I think it's a great way of ensuring customer engagement for those operations you can't avoid taking a little time.

**Comment by jaddie** [comment]
This one looks like its done with?

P.S Love reading your explanations @stoiveyp literally so quickly informative and straight forward!
