### ISSUE TITLE
Cannot serialize member Alexa.NET.Request.Session.Attributes of type System.Collections.Generic.Dictionary`

### ISSUE THREAD

**Issue by sp823** [timheuer/alexa-skills-dotnet#111]
I am getting the following chain of errors at run-time related to the public method in the sample code taking a SkillRequest as a parameter. I'm sure it must be something simple but not sure what it is. All the dependencies are being deployed to the IIS application. I added Amazon.Lambda.Core to get it to build (for ILambdaContext).

[NotSupportedException: **Cannot serialize member Alexa.NET.Request.Session.Attributes of type System.Collections.Generic.Dictionary`2**[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], because it implements IDictionary.]
[InvalidOperationException: There was an error reflecting type 'Alexa.NET.Request.Session'.]
[InvalidOperationException: There was an error reflecting property 'Session'.]
[InvalidOperationException: There was an error reflecting type 'Alexa.NET.Request.SkillRequest'.]
[InvalidOperationException: There was an error reflecting 'input'.]
[InvalidOperationException: Method BadService.FunctionHandler can not be reflected.]
[InvalidOperationException: Unable to handle request.]
[InvalidOperationException: Failed to handle request.]

**Comment by stoiveyp** [comment]
Hi @sp823 - couple of things.

Can you confirm your code is expecting JSON output, or has a content type set to application/json?

If that is the case, could you also confirm what version of the .NET Framework you're using to build your application.

Thanks ever so much

**Comment by sp823** [comment]
Thanks for the quick response. I get the error just trying to pull up the web service in a browser to inspect the wsdl or instantiating it in a test project. I do not get to the point where I can actually call any public methods. If the method is there and takes/returns the SkillRequest/SkillResponse types I just can't do anything with the web service at all. 

My project is targeting 4.6.1.

**Comment by stoiveyp** [comment]
Thanks for the extra info. A traditional web service project with a wsdl would tend to expect XML input and output - which isn't compatible with Alexa, which requires JSON. The error you've given could come from the Dictionary objects in our model serialised by the the XmlSerializer.

Ideally this needs to be run within a Web API project, or JSON needs to be the defined schema for input and output.

Does that help clear things up a little?

**Comment by jaddie** [comment]
This seems to be a dead issue and can be closed?
