### ISSUE TITLE
New Skill Standard?

### ISSUE THREAD

**Issue by dyl10s** [timheuer/alexa-skills-dotnet#112]
So I made a quick skill yesterday and got this feedback from amazon. 

Future versions of the Alexa Skills Kit may add new properties to the JSON request and response formats, while maintaining backward compatibility for the existing properties.  When we invoke the skill with additional parameters, the skill is rejecting it when we expect this to be accepted.  Your code must be resilient to these types of changes. For example, your code for de-serializing a JSON request must not break when it encounters a new, unknown property. 

I assume this has to do with how the skill initially serialized the data. Is there any way I can catch this error?

**Comment by stoiveyp** [comment]
Hey @dyl10s - our deserialization shouldn't break if Amazon add properties, as JSON.NET will explicitly ignore anything it doesn't know about. They've added a few bits and pieces over time, especially around slot values, and we've upgraded without trouble.

How are you hosting the skill? As that's going to change what options are open to you. Hopefully there's some error information in your logs though, as that would at least tell us whereabouts in the model there appears to be a problem.

Cheers

**Comment by dyl10s** [comment]
Its hosted on AWS lambda.

**Comment by stoiveyp** [comment]
Brilliant - then any exceptions in the JSON deserialization should have caused an error record in the CloudWatch logs for that function, hopefully that'll let us know which part of the skill caused an issue.

If you actually want to catch it yourself in code - you can change the skillRequest reference to a string and then run the deserialization code manually with a try/catch.

If you just want easy logs when it happens to help track down the problem, then you can add LAMBDA_NET_SERIALIZER_DEBUG to true within the lambda environment variables - and that will log all requests & responses coming through the lambda so you can see exactly what's happening.

**Comment by dyl10s** [comment]
Ahh perfect ok, I was wondering if I could change the input to a string. That will work.
