### ISSUE TITLE
v1.5.5 didn't make it to NuGet

### ISSUE THREAD

**Issue by stoiveyp** [timheuer/alexa-skills-dotnet#113]
Hey Tim

Thanks for merging in the Polly support, much appreciated as always. You bumped the version to 1.5.5 to support this, but NuGet is still saying 1.5.5-pre was the last update.

Just hoping nothing's happened with my merged code to cause a problem? When you get chance would you mind seeing if everything's okay with the deployment pipeline?

Thanks again

**Comment by timheuer** [comment]
Nothing wrong with the code, it's the deploy pipeline.  I'm wanting to debug before i manually upload.  The VSTS transfer to Azure Pipelines...suddenly it isn't finding the nuget package to deploy so I'm working through that.

**Comment by timheuer** [comment]
Fixed!
