### ISSUE TITLE
Error with signature verification

### ISSUE THREAD

**Issue by qmatteoq** [timheuer/alexa-skills-dotnet#114]
Hello,
I'm trying to use the RequestVerification.Verify() method in the following way:

```
public async static Task<IActionResult> Run(
[HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)]
HttpRequest request, ILogger log)
   {
        log.LogInformation("Function triggered");
        Uri signatureCertChainUrl = new Uri(request.Headers["SignatureCertChainUrl"]);
        string signature = request.Headers["Signature"];

        string json = await request.ReadAsStringAsync();

        bool isValid = await RequestVerification.Verify(signature, signatureCertChainUrl, json);

        if (isValid)
        {
            return new OkResult();
        }
        else
        {
            return new BadRequestResult();
        }
    }
```

Of course this is just a simplification. My real method doesn't simply return OkResult, but it contains all the code to interact with the user using voice commands.

The problem is that the Verify() method always raises the following exception:

> System.Net.Http: The requested name is valid, but no data of the requested type was found. System.Private.CoreLib: The requested name is valid, but no data of the requested type was found

If I try to verify just the signatureCertChainUrl it works, but it seems to not be enough for Amazon since the technical validation phase of the submission always fails.

Can you help?
Thanks!

**Comment by qmatteoq** [comment]
Thanks! You pointed me to the right direction and I found it was the DNA in my house which was blocking the request. Changing it or pushing the project to Azure solved the problem.

Speaking of security requirements, did you have ever published an Alexa skill built with Alexa.net? It seems that, despite in my code I'm returning 400 if both the Verify() method and the VerifyTimestamp() return false, the validation process by Amazon is still complaining that my function accepts requests with an invalid signature.

**Comment by IcanBENCHurCAT** [comment]
@qmatteoq I was never able to get verification to work on heroku, even with the middleware plugin specifically made to solve it. I eventually migrated to AWS lambda and have had no issues with it. If you've got the logs from the Amazon tests maybe we could put together which requests are responding successfully and look at their signatures?

**Comment by qmatteoq** [comment]
Hello @IcanBENCHurCAT ,
I've been able to get everything up and running thanks to the RequestVerification.Verify() method. In this blog post I've detailed all the steps I've followed to get it up & running: https://blogs.msdn.microsoft.com/appconsult/2018/11/03/build-your-first-alexa-skill-with-alexa-net-and-azure-functions-the-certification/

In my case, the skill is hosted on Azure using an Azure Function. Let me know if I can help with more information!

**Comment by SuavePirate** [comment]
Using @qmatteoq's code for validation from the above blog post but with an Azure App Service and ASP.NET Core, I get the following errors from Functional Tests. Was there some other step too? I had to make some slight changes since the `HttpRequest` model is slightly different.

![image](https://user-images.githubusercontent.com/6868294/48494516-0e26d180-e7fc-11e8-8846-ffb90955e771.png)

Specifically, here is my code for validate:
```csharp
private async Task<bool> ValidateRequest(HttpRequest request, SkillRequest skillRequest)
{
    try
    {
        request.Headers.TryGetValue("SignatureCertChainUrl", out var signatureChainUrl);
        if (string.IsNullOrWhiteSpace(signatureChainUrl))
        {
            return false;
        }

        Uri certUrl;
        try
        {
            certUrl = new Uri(signatureChainUrl);
        }
        catch
        {
            return false;
        }

        request.Headers.TryGetValue("Signature", out var signature);
        if (string.IsNullOrWhiteSpace(signature))
        {
            return false;
        }

        // this stuff is slightly different for validating the body. Could this be the problem?
        var body = "";
        request.EnableRewind();
        using (var stream = new StreamReader(request.Body))
        {
            stream.BaseStream.Position = 0;
            body = stream.ReadToEnd();
            stream.BaseStream.Position = 0;
        }

        if (string.IsNullOrWhiteSpace(body))
        {
            return false;
        }

        bool isTimestampValid = RequestVerification.RequestTimestampWithinTolerance(skillRequest);
        bool valid = await RequestVerification.Verify(signature, certUrl, body);

        if (!valid && !isTimestampValid)
        {
            return false;
        }
        else
        {
            return true;
        }

    }
    catch
    {
        return false;
    }
}
```

**Comment by qmatteoq** [comment]
Hello @SuavePirate ,
I apologize, I exactly stumbled across the same issue and I realized my code contained a typo. The final check of the method should be:

`
if (!valid || !isTimestampValid)
{
    return false;
}
else
{
    return true;
}
`

You need to replace the && (and) with || (or). Otherwise if Alexa send a request with an invalid signature but a valid timestamp, the function will correctly return true.
I apologize for the mistake, also the code on the blog is fixed now.

**Comment by SuavePirate** [comment]
Oh man, I can't believe I didn't catch that! Thank you so much for responding within literally 5 minutes lol. Life saver.

Worked perfectly btw.

**Comment by bragma** [comment]
Have you tried the "Alexa.NET.Security.Functions" package? It makes request validation trivial.
