### ISSUE TITLE
Remove Session Attibutes in Intent Response - Question

### ISSUE THREAD

**Issue by anandmukundan** [timheuer/alexa-skills-dotnet#116]
Hi,

I have a multi-step dialog and I use the session attributes to track some state. I am not sure how to remove a session attribute after I use it.

E.g.

Step 1 - Ask for slot 1.
Step 2- Do some processing on slot 1, add a session attribute to track data and ask for slot 2
Step 3 - Do more processing with data I have, remove the previous session attribute as I do not need it, send some response to user, and ask for slot 3.

I don't end my response and have a session open for other intents too. So do not want intermediate session attributes to hang on till the session ends.

I add session attributes via the response.sessionattributes, but I not sure how do I remove a session attribute that I got via the request?

Thanks

**Comment by stoiveyp** [comment]
Hi @anandmukundan 

The session attributes are a dictionary object - so you can use `session.Remove(key)` to remove an item from an active session object.

Also, the response session and the request session can be different, so you can do something like 
```csharp
var session = new Session();
session.Attributes = new Dictionary<string,object>();
session.Attributes.Add(justOneKey,justOneValue);
response.SessionAttributes = session;
```

Hope this helps

**Comment by anandmukundan** [comment]
Hi @stoiveyp,

Thanks, that I what I was trying to do. 
E.g.
handler (SkillRequest request)
{
return [SkillResponse] //Say via a ResponseBuilder...
}

So if I do request.Session.Attributes.Remove("myKey"), then the next request from Alexa will not have this attribute? 

I did try doing something like response.SessionAttributes = new Dictionary and sent back an empty dictionary, but the next request still had the sesssion attribute I had added in the previous response.

**Comment by anandmukundan** [comment]
Hi @stoiveyp 

There was a problem with my code.. When I tried with response.SessionAttributes= new dictionary, it does clear out the data from the next request. So that option did work.

The request Session as you mentioned is separate and looks like that is not sent to the caller, so any operations on that dictionary does not propagate to the next call.

Thanks..
