### ISSUE TITLE
Alexa.Net.Request.Context deserialization issue today

### ISSUE THREAD

**Issue by kikenoteges** [timheuer/alexa-skills-dotnet#118]
Last friday (2/11/2018) my solution works. Today it does not.

This is the error when I try to call the lambda with the call which works the firstly. Any clue?
{
  "errorType": "JsonSerializationException",
  "errorMessage": "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Alexa.NET.Request.Context' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\nPath 'context', line 13, position 14.",
  "stackTrace": [
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
    "at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
    "at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)",
    "at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)",
    "at AlexaCalculator.Function.FunctionHandler(Object input, ILambdaContext context) in D:\\OtherProjects\\AlexaCalculator\\AlexaCalculator\\Function.cs:line 33",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ]
}

More info: I have just update JsonConvert to v11 and I've got a new message:

{
  "errorType": "JsonSerializerException",
  "errorMessage": "Error converting the Lambda event JSON payload to type Alexa.NET.Request.SkillRequest: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Alexa.NET.Request.Context' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\nPath 'context', line 1, position 207.",
  "stackTrace": [
    "at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ],
  "cause": {
    "errorType": "JsonSerializationException",
    "errorMessage": "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Alexa.NET.Request.Context' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\nPath 'context', line 1, position 207.",
    "stackTrace": [
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
      "at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
      "at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)",
      "at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)"
    ]
  }
}

**Comment by timheuer** [comment]
What version of the lib are you using?

**Comment by kikenoteges** [comment]
1.5.5

**Comment by timheuer** [comment]
Can you rollback and just confirm 1.5.4 works fine?

**Comment by timheuer** [comment]
@stoiveyp have you seen this?  It feels almost like an error in the Lambda response.

**Comment by stoiveyp** [comment]
@timheuer The JSON.Net error seems to be indicating that the skill request being deserialized has found the context property, but that it's finding the start of an array, rather than an object.

We've not updated context in quite some time (that's why I kept APL

**Comment by timheuer** [comment]
Yeah I wonder if AWS has updated the object to return Array instead of Object...hmmm, definitely looks like an issue with what is being sent.

**Comment by stoiveyp** [comment]
Hmm I'm editing one at the moment (issue with APL support) and context is definitely an object, but wouldn't be the first time they've been a little inconsistent between clients.

@kikenoteges is the request you're deserializing coming from a physical device? We've had issues before where the test tools in Alexa Developer Console have been slightly out of sync.

Is it possible for you to retrieve the request as a string to show us the start of the context object? It seems like there might be an issue around that bit of text.

**Comment by kikenoteges** [comment]
> Hmm I'm editing one at the moment (issue with APL support) and context is definitely an object, but wouldn't be the first time they've been a little inconsistent between clients.
> 
> @kikenoteges is the request you're deserializing coming from a physical device? We've had issues before where the test tools in Alexa Developer Console have been slightly out of sync.
> 
> Is it possible for you to retrieve the request as a string to show us the start of the context object? It seems like there might be an issue around that bit of text.

Here is the Json that Alexa Console is sending to the lambda (I got it from from the Alexa's log). 

When I tested the lambda function with this JSON, it shows the error I copied in the first posts.

By the way, thanks for your support guys ;).

`{
  "event": {
    "header": {
      "namespace": "Text",
      "name": "TextMessage",
      "messageId": "messageId",
      "dialogRequestId": "8b50b4e9-9306-48d8-a9ec-e72ff30e7616"
    },
    "payload": {
      "textMessage": "alexa, open number facts"
    }
  },
  "context": [
    {
      "header": {
        "namespace": "System",
        "name": "SettingsState",
        "payloadVersion": "1"
      },
      "payload": {
        "settings": [
          {
            "key": "com.amazon.alexa.characteristics.viewport.experiences",
            "value": "[{\"arcMinuteWidth\":\"246\",\"arcMinuteHeight\":\"144\",\"canRotate\":\"false\",\"canResize\":\"false\"}]"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.shape",
            "value": "RECTANGLE"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.pixelWidth",
            "value": "1024"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.pixelHeight",
            "value": "600"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.dpi",
            "value": "160"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.currentPixelWidth",
            "value": "1024"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.currentPixelHeight",
            "value": "600"
          },
          {
            "key": "com.amazon.alexa.characteristics.viewport.touch",
            "value": "[\"SINGLE\"]"
          }
        ]
      }
    },
    {
      "header": {
        "namespace": "SpeechSynthesizer",
        "name": "SpeechState"
      },
      "payload": {
        "token": "",
        "offsetInMilliseconds": 0,
        "playerActivity": "PLAYING"
      }
    },
    {
      "header": {
        "namespace": "AudioPlayer",
        "name": "PlaybackState"
      },
      "payload": {
        "token": "",
        "offsetInMilliseconds": 0,
        "playerActivity": "IDLE"
      }
    },
    {
      "header": {
        "namespace": "Alerts",
        "name": "AlertsState"
      },
      "payload": {
        "activeAlerts": [],
        "allAlerts": []
      }
    },
    {
      "header": {
        "namespace": "AudioFocusManager",
        "name": "AudioFocusState"
      },
      "payload": {}
    }
  ]
}`

**Comment by timheuer** [comment]
Just to confirm @kikenoteges:
- this is the same JSON used when it was working prior?
- if you rollback to 1.5.4 does this work with this payload?

**Comment by stoiveyp** [comment]
@kikenoteges sorry to add to the requests, but when you say the Alexa's log, whereabouts do you mean? This looks like a device log entry from the developer console, which isn't the format we'd expect to see. Could you possibly send a screenshot or give a little more detail?

Thanks

**Comment by timheuer** [comment]
Yeah this looks like an odd request format.  The type of 'Text message' is throwing me off too.

**Comment by stoiveyp** [comment]
I think I may have it - this syntax seems to match an AVS request https://developer.amazon.com/docs/alexa-voice-service/system.html

Is it possible an option other than custom was picked when creating the skill?

**Comment by stoiveyp** [comment]
@kikenoteges Thank you, that's really helpful!

That part of the screen you're seeing is the device log - which is used for AVS debugging, and isn't supported by Alexa.NET

If you scroll to the top of the screen, or uncheck the Device Log and Device Display boxes at the top of the screen, you should see a section labelled "Skill I/O" - which is the JSON that is sent to your Lambda by an Alexa skill, and should look like the screenshot below. If you use that to test your skill, you'll see the deserialization works as expected.

I hope this helps

![alexascreen](https://user-images.githubusercontent.com/147125/48085684-e380bb80-e1f2-11e8-8f8f-2151303369e8.png)

**Comment by stoiveyp** [comment]
The other screenshot your partners are working with? I don't believe that's the same kind of service. 

Alexa.NET is for custom skills, but the request you're showing your node team working on in the screenshot looks like AVS, or Alexa Voice Service - an example of an AVS request is here: https://developer.amazon.com/docs/alexa-voice-service/enable-named-timers-and-reminders.html#setalert

Neither 1.5.4 or 1.5.5 of Alexa.NET should be able to work with the JSON you're showing us, it's expecting the format I'm showing in my screenshot.

Do you get values in the SkillRequest object when you send that JSON directly to your lambda?

**Comment by kikenoteges** [comment]
Sorry, I didn't explain myself right. All the screen are from my project. But I work with other two partners, one with GO and other with Node.js. Both seem to have weird issues as we have with Alexa.Net. The work getting the json that Alexa console print on screen (which I did on my first app that is working and also approved in the market). Because of the way or try the lambda was the same in all the languages, It is too strange for me that now this process stops working.

I just let you know that it seems that Amazon has not a very mature product for developers xD.

Ok, I will try that you said to me.

**Comment by kikenoteges** [comment]
Ok, it works @stoiveyp ! Thanks for that tip. I upload the test on lambda. I will finish creating the new sample project to see if there are any other problems.
![image](https://user-images.githubusercontent.com/17978931/48315805-279d0300-e5db-11e8-80ed-1606526dcf0e.png)

**Comment by kikenoteges** [comment]
Issue closed yep!

So the thing here is that I was getting the wrong json (from de log). I can't explain why the other project worked but... whatever sometimes is better to be into the beautiful knowledge darkness (for mental sanity purposes)

Thank you very much, guys. Now, I think I can put any new basic skill in about half an hour without problems. If you would help me, you could try to install Number Facts, which uses an api to tell you funny things about dates and numbers. Also, I'm from Spain and if 50 people get the app Amazon send me an Echo for free ^^.
