### ISSUE TITLE
StandardCard: Text property mislabeled

### ISSUE THREAD

**Issue by bjorg** [timheuer/alexa-skills-dotnet#12]
According to this article, the `StandardCard` should have a `Text` property instead of a `Content` property like the `SimpleCard`: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app#creating-a-home-card-to-display-text-and-an-image

**Comment by timheuer** [comment]
Good find.  Verifying with Alexa team this isn't just a typo.

**Comment by timheuer** [comment]
This was fixed by #24 -- while the API property remains unchanged to preserve breaking change impact and not have two duplicate properties (or obsolete one), the JSON property data is corrected.
