### ISSUE TITLE
CanFullFillIntent

### ISSUE THREAD

**Issue by anandmukundan** [timheuer/alexa-skills-dotnet#121]
Hi,

I don't see support for CanFullFillIntent support in the master branch, but I do see it in the beta branch? Also there seems to be no preview nuget branches. I had two questions?

1. Is the CanFullFill implementation not merged to master because it is not stable? It seems to have been committed in July and the latest release of the library is in Nov?
2. If I a want to play around with support for CanFullFill what options do I have? The beta branch seems to had no commits after Jun, so I assume it does not have any of the newer features like Polly etc..?

Thanks,

**Comment by timheuer** [comment]
Hi @anandmukundan the beta NuGet is here: https://www.nuget.org/packages/Alexa.NET/1.5.5-pre which includes the CanFulfillIntent -- you are correct that the beta package does not include Polly, etc. but we should refresh that with a merge.

I don't think CanFulfillIntent is in stable yet so that's why we haven't merged to master.

**Comment by anandmukundan** [comment]
Thanks @timheuer I will try out the beta version from nuget.

**Comment by anandmukundan** [comment]
True @timheuer. I did test the beta version and it was able to handle the CanFullfill request. But the only way I could find to test is via Manual JSON.
I did see there are some skills in Production that seem to use this, but I suppose Amazon is keeping this in preview as it is not really easily testable and they want to gather more data before they move this out of preview.

**Comment by jasoncable** [comment]
I've tested it manually with JSON.  It seems to work fine.  I really like your API.  It made getting my first skill up without much issue.

**Comment by timheuer** [comment]
Great!  Hopefully this will come out of preview soon.

**Comment by nishantpant** [comment]
I implemented CanFulfillIntentRequest months ago and Alexa randomly pings my skill for it. Just here to report that it is working. Maybe you should merge into master

**Comment by hattabatatta** [comment]
Any updates on that?
Will there be some examples at the main page then?

**Comment by timheuer** [comment]
@stoiveyp do you know if CanFulfillIntentRequest is officially in now and we can merge this official?

**Comment by stoiveyp** [comment]
@timheuer According to the Beta and Preview list it's still Beta

https://developer.amazon.com/alexa-skills-kit/features/beta-developer-preview

Does seem to be taking a while. I could isolate the request into an extension the same way we have with things like APL?

**Comment by stoiveyp** [comment]
I've moved forward with this idea and, until it's out of beta at least, there's this new extension

https://www.nuget.org/packages/Alexa.NET.CanFulfillIntentRequest/1.0.0

Think it allows the correct use cases, but feel free to raise issues against the extension if I've missed something.

**Comment by apregister08** [comment]
@stoiveyp 

I am having an issue with the package Alexa,NET.CanFulfillIntentRequest.  Maybe I am not implementing it right.  It appears serialization is failing for me before my Lambda function is called.  I am using Alexa.NET 1.8.2 and Alexa.NET.CanFulfillIntentRequest 1.1.0.

**REQUEST**
{
  "request": {
    "type": "CanFulfillIntenRequestt",
    "requestId": "amzn1.echo-api.request.80b2d1a6-7e0f-4d8a-b0ac-aa12623bbe6b",
    "intent": {
      "name": "ReadStoryIntent",
      "slots": {}
    },
    "locale": "en-US",
    "timestamp": "2019-10-10T02:52:33Z"
  },
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.30dd95e8-04f5-46cb-8777-d0f94d288fbf"
      },
      "user": {
        "userId": ""
      },
      "device": {
        "supportedInterfaces": {}
      }
    }
  },
  "version": "1.0"
}`

**RESPONSE**

{
  "errorType": "JsonSerializerException",
  "errorMessage": "Error converting the Lambda event JSON payload to type Alexa.NET.Request.SkillRequest: Unknown request type: CanFulfillIntenRequest.\nParameter name: Type",
  "stackTrace": [
    "at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ],
  "cause":   {
    "errorType": "ArgumentOutOfRangeException",
    "errorMessage": "Unknown request type: CanFulfillIntenRequestt.\nParameter name: Type",
    "stackTrace": [
      "at Alexa.NET.Request.Type.RequestConverter.Create(String requestType)",
      "at Alexa.NET.Request.Type.RequestConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
      "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
      "at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
      "at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)",
      "at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)"
    ]
  }
}

**Comment by anandmukundan** [comment]
You seem to have an extra "t" at the end of type in your request ("type": "CanFulfillIntenRequestt").

**Comment by apregister08** [comment]
That was a typo.  But the issue still remains.

**Comment by stoiveyp** [comment]
@apregister08 Okay - I was going to pick up on the incorrect Request Type too. If it's a typo are you manually testing the code at the moment?

If you have the same issue with the correct request type - then that error should only appear if the converter hasn't been registered. Have you got the this line somewhere in your startup code?

`CanFulfillIntentRequestConverter.AddToRequestConverter();`

**Comment by apregister08** [comment]
Yes, I am doing manual testing from within Visual Studio connected to my Lambda.   In my Function method, I have `CanFulfillIntentRequestConverter.AddToRequestConverter();` right after:

```
public SkillResponse FunctionHandler(SkillRequest skillrequest, ILambdaContext lamdbaContext)
{
       CanFulfillIntentRequestConverter.AddToRequestConverter();
      .........

```

**Comment by stoiveyp** [comment]
Yeah that's the problem - the converter has to be added to the lambda before your function handler gets invoked - otherwise when your request tries to create the right SkillRequest, there's no code for that kind of request available and generates the error.

To fix it create a constructor for the lambda, then move the converter registration into the constructor - that way when the function is invoked the converter is already registered and it should create the right SkillRequest.

Hope this helps

**Comment by apregister08** [comment]
Yes!  It is working.  I also had to make some tweets to my request.  Thanks for your help and all your hard work guys.
