### ISSUE TITLE
Alexa Skill - Account linking and its card

### ISSUE THREAD

**Issue by UsamaAslam** [timheuer/alexa-skills-dotnet#122]
Hello ,
I am using Alexa for my new project in which i need user to link their Account for the first time and then i need those credentials in backend so i want to account link. 

Trying to build a skill which makes use of an api to upload the information obtained by the end user, and cant seem to locate a detailed guide for .Net, 
We essentially would require three parameters from the user, the base url of their api as well as the username and password. Which method and how? Would be best for this and would this be possible to get this information through the account linking card

@stoiveyp Thanks for your help in Advance .

**Comment by stoiveyp** [comment]
Requirements for account linking is that the account system you're hooking into has to be available through OAuth2.

More information about the technical implementation is available here: https://developer.amazon.com/docs/account-linking/understand-account-linking.html

The account linking card just allows the user to start the OAuth2 journey from a device by clicking on then card.

**Comment by jaddie** [comment]
This looks like it might as well be closed too? :)
