### ISSUE TITLE
High level - how to use this project?

### ISSUE THREAD

**Issue by crilecarvey** [timheuer/alexa-skills-dotnet#124]
I'm feeling dumb, but can someone point me to a super basic starter resource that uses this library?  I have built skills using my own kinda homegrown stuff using ASP.NET MVC where I have an AlexaController that serves up json ActionResult responses. Is that the approach you are taking? I have a feeling I am a acting like a dinosaur among robots...

**Comment by stoiveyp** [comment]
Hi @crilecarvey - rather than using JSON, we use a strongly typed model to represent the requests and responses.

I've got a repo with a few serverless examples here: https://github.com/stoiveyp/Alexa.NET.Samples

**Comment by crilecarvey** [comment]
thanks
