### ISSUE TITLE
SkillRequest.GetRequestType() not needed in C# 7 anymore

### ISSUE THREAD

**Issue by bjorg** [timheuer/alexa-skills-dotnet#13]
With pattern matching on types in C# 7, the `GetRequestType()` method is not useful anymore. It's much easier just do to:
```
switch(skillRequest.Request) {
case LaunchRequest launch:
    ...
case IntentRequest intent:
   ...
}
```

**Comment by timheuer** [comment]
This is more of a consumer of the SDK rather than implementation in this project.  We'll keep the GetRequestType() for now as it is used in some tests.
