### ISSUE TITLE
SessionEndedRequest and Error

### ISSUE THREAD

**Issue by anandmukundan** [timheuer/alexa-skills-dotnet#132]
One of the items in the SessionEndedRequest is an error object if the reason is an error. Currently though I can access the Reason value, there is no property to access the error object.

Is there any other way to access this currently?

{
    "type": "SessionEndedRequest",
    "requestId": "amzn1.echo-api.request.33504577-0a64-4292-b733-1f7f5ab53161",
    "timestamp": "2019-03-03T17:16:19Z",
    "locale": "en-US",
    "reason": "ERROR",
    **"error": {
        "type": "INVALID_RESPONSE",
        "message": "Invalid SSML Output Speech for requestId amzn1.echo-api.request.448ddb45-d25e-42d4-b9d0-4cbbac291c82. Error: Invalid SSML element prodody"**
    }
}

**Comment by stoiveyp** [comment]
Good catch @anandmukundan - looks like they've added the error object from SystemExceptionRequest into the SessionEndedRequest.

Created a PR for the necessary change.
