### ISSUE TITLE
Alexa.Net Reminder cannot create reminder: throws error

### ISSUE THREAD

**Issue by saikat2k01** [timheuer/alexa-skills-dotnet#136]
While using the code base from the project to create a reminder, I get the following error:
Error at Alexa.NET.Response.RemindersClient.d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AlexaWebAPI.Controllers.ReminderController.d__0.MoveNext()

Can you please help me understand what is going wrong here.
Code Snippet used to create reminder:
`var reminder = new Reminder
{
RequestTime = DateTime.UtcNow,
Trigger = new RelativeTrigger(12 * 60 * 60),
AlertInformation = new AlertInformation(new[] { new SpokenContent("it's a test", "en-GB") }),
PushNotification = PushNotification.Disabled
};
var client = new RemindersClient(RemindersClient.ReminderDomain,input.Session.User.AccessToken);
var alertDetail = await client.Create(reminder);](url)`

**Comment by stoiveyp** [comment]
@saikat2k01 could you please put a try/catch around the `await client.Create`
The exception message you get back from that should be more detailed and can help us determine the problem

**Comment by raymondjstone** [comment]
Reminders work fine for me, you do need to set BOTH permissions, firstly for the skill itself in the developer console and secondly for your account in the alexa website (it is not available to set in the alexa app here). If setting a recurring reminder you must set the days of week list as well as the initial date (why if the frequency is weekly they mandate this I have no idea)
