### ISSUE TITLE
Error while deserializing System.ExceptionEncountered request

### ISSUE THREAD

**Issue by marcominerva** [timheuer/alexa-skills-dotnet#137]
When I try to deserialize the following request:

```
{
   "version":"1.0",
   "context":{
      "AudioPlayer":{
         "offsetInMilliseconds":0,
         "token":"0",
         "playerActivity":"PLAYING"
      },
      "System":{
         "application":{
            "applicationId":"amzn1.ask.skill.91ff9456-9cfe-4cc6-a9bc-41e0187b382a"
         },
         "user":{
            "userId":"..."
         },
         "device":{
            "deviceId":"...",
            "supportedInterfaces":{
               "AudioPlayer":{

               },
               "Geolocation":{

               }
            }
         },
         "apiEndpoint":"https://api.eu.amazonalexa.com",
         "apiAccessToken":"..."
      }
   },
   "request":{
      "type":"System.ExceptionEncountered",
      "requestId":"amzn1.echo-api.request.ae544ebc-e9ff-4e98-a93c-4753ae95a85f",
      "timestamp":"2019-05-19T10:02:26Z",
      "locale":"it-IT",
      "error":{
         "type":"INVALID_RESPONSE",
         "message":"A Play directive with the ENQUEUE play behavior must have an expected token"
      },
      "cause":{
         "requestId":"amzn1.echo-api.request.315d6412-7812-4001-bbc2-e6ac7a11c8aa"
      }
   }
}
```

Using this code (I'm in an Azure Functions):

```
var json = await req.ReadAsStringAsync();
var skillRequest = JsonConvert.DeserializeObject<SkillRequest>(json);
```

I obtain the following error:

> Unknown request type: System.ExceptionEncountered.
> Parameter name: Type

**Comment by stoiveyp** [comment]
Hi @marcominerva 

I know we've had issue with Azure Functions and customConverters before, but not with that kind of code example. First of all, can I confirm you're on the latest version of Alexa.NET? If so... 

The error is ours - https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/Type/RequestConverter.cs#L49

But the code to handle System.ExceptionEncountered is here:
https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/Type/Converters/DefaultRequestTypeConverter.cs#L20

So it should be finding the converter. Makes me think it might be something to do with the static setup of the JsonConverters. Hmm... 

Are you able to use Function model binding to set the request instead? See if that helps the issue go away? Got an old example here - but I believe the syntax for the function argument is still good?

https://github.com/stoiveyp/Alexa.NET.Samples/blob/master/AzureFunction/Function1.cs

**Comment by stoiveyp** [comment]
Scrap all that - just seen that the DefaultRequestTypeConverter CanConvert method is missing the System.ExceptionEncountered type 🤦‍♂

**Comment by stoiveyp** [comment]
Created PR #138 for fix
