### ISSUE TITLE
How AudioPlayerRequest.HasEnqueuedItem property works?

### ISSUE THREAD

**Issue by marcominerva** [timheuer/alexa-skills-dotnet#139]
I'm using the last version of Alexa.NET. I see that the **AudioPlayerRequest** contains a boolean property named **HasEnqueuedItem**. However, this property isn't described in the Amazon documentation at https://developer.amazon.com/it/docs/custom-skills/audioplayer-interface-reference.html. So, how is it supposed to work?

**Comment by stoiveyp** [comment]
Hi @marcominerva - it's a helper method. Returns a Boolean based on the existence of the EnqueueToken.

Code is available here: https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/Type/AudioPlayerRequest.cs#L35

**Comment by marcominerva** [comment]
Thank you. So I have searched for [enqueuedToken](https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/Type/AudioPlayerRequest.cs#L23) in the Alexa documentation at https://developer.amazon.com/it/docs/custom-skills/audioplayer-interface-reference.html, but I haven't found this property. Am I searching in the wrong place? :-)

**Comment by stoiveyp** [comment]
Right - see what you're saying. Looks like AudioPlayer hasn't been looked at for a couple of years, my guess is the interface has changed slightly - but not so much that it broke the library in its current state.

**Comment by marcominerva** [comment]
Yes, I see that the points for which the library needs to be updated are the _enqueuedToken_ managament and support for metadata in the **AudioPlayerPlay** directive.
