### ISSUE TITLE
Implementation of the deviceId

### ISSUE THREAD

**Issue by davidkirberich** [timheuer/alexa-skills-dotnet#14]
Concerning this paper, it is possible to retrieve the deviceId from device object:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/device-address-api#steps

> deviceId = this.event.context.System.device.deviceId

At the moment it's not implemented in Alexa.NET, but I think it may be useful.

PS: Awesome work, Tim! I showed Alexa.NET to Amazon people in Germany and they were suprised how comfortable it is to build skills \w Visual Studio + .NET Core + AWS Plugin + Alexa.NET

**Comment by timheuer** [comment]
This is interesting!  Looks like some new options.  To really do it right I think we need to implement the full permission card, etc.

**Comment by StenmannsAr** [comment]
#16 
Sry I saw it to late, after the pull request.

To get the address you must make a http-request to the endpoint with the deviceid and the consentToken as Bearer token.

I made a function for this, but i don't know that this function just fit in this library?

**Comment by davidkirberich** [comment]
In my opinion the **retrieval** of the consentToken isn't part of this library's job, but de/serialization is. Otherwise dependencies to other packages would increase.

At the moment I think about a Manager package for Alexa.NET which uses the fluent pattern to build skills from scratch. A helper class for the Device Address API would perfectly fit into that.

**Comment by StenmannsAr** [comment]
The consentToken is a part of the Alexa-API like the other Attributes like itents... so it fits perfectly into this library. 

But the use of the consentToken and the endpoint should not be a part of Alexa.NET.

**Comment by davidkirberich** [comment]
That's exactly what I meant :)

**Comment by timheuer** [comment]
Resolved as a merge of #16 thanks @StenmannsAr
