### ISSUE TITLE
Missing ViewPort in SkillRequest.Context

### ISSUE THREAD

**Issue by PabloBenigno** [timheuer/alexa-skills-dotnet#158]
Hello, I have the fix in a local repository, but I cannot push to origin, cause I don't have permissions. How can I contribute to this awesome project? :)

**Comment by PabloBenigno** [comment]
For information about the field:
https://developer.amazon.com/es/docs/alexa-presentation-language/apl-viewport-characteristics.html

**Comment by stoiveyp** [comment]
Hey @PabloBenigno - check out the Alexa.Net.APL support in the extensions list, it has an updated skill request and full support for APL 1.0 and (as of about an hour ago) 1.1

I maintain it seperately to the core project :+1:

**Comment by stoiveyp** [comment]
In answer to your question, to contribute you can fork the project, then submit a Pull Request from your fork. Hope this helps moving forward.

**Comment by PabloBenigno** [comment]
Thanks for the info and for this great project :)
