### ISSUE TITLE
Missing UpdateDynamicEntities Directive in converter

### ISSUE THREAD

**Issue by luis7722** [timheuer/alexa-skills-dotnet#164]
I found Dialog.UpdateDynamicEntities missing in Converter:
Alexa.NET/Response/Converters/DirectiveConverter.cs

**Comment by timheuer** [comment]
Thanks for the issue @luis7722.  Are you using this directive right now and you are blocked?

**Comment by luis7722** [comment]
Yes, i´m using it and when I try to deserialize the ResponseBody, it shows Dialog.UpdateDynamicEntities is not recognized in JsonConvert.DeserializeObject<ResponseBody>

**Comment by timheuer** [comment]
Ok thanks.  @stoiveyp have you used this directive at all in your apps yet?

**Comment by luis7722** [comment]
Thanks for the help and response

**Comment by stoiveyp** [comment]
Sorry for the delay, still catching up post-vacation. DirectiveConverter is extensible so the immediate workaround is

`DirectiveConverter.TypeFactories.Add("Dialog.UpdateDynamicEntities",() => new DialogUpdateDynamicEntities());`

I should have spotted it needed adding to the default list when I created it though - Ill sort out a quick PR 👍

**Comment by timheuer** [comment]
Thanks for the quick PR @stoiveyp as always!!!  Will merge now into a 1.8.1
