### ISSUE TITLE
System.ExceptionEncountered: SpeechletResponse was null

### ISSUE THREAD

**Issue by bjorg** [timheuer/alexa-skills-dotnet#17]
Apparently Alexa expects `{}` for empty responses (e.g. responses to `AudioPlayer` requests). As far as I can tell, that's not possible with the current `SkillResponse` class.

Here's the warning I've been seeing in CloudWatch logs.
```
{
    "version": "1.0",
    "session": null,
    "context": {
        "System": {
            "application": {
                "applicationId": "..."
            },
            "user": {
                "userId": "...,
                "accessToken": null
            },
            "device": {
                "supportedInterfaces": {
                    "AudioPlayer": {}
                }
            }
        },
        "AudioPlayer": null
    },
    "request": {
        "error": {
            "type": "INVALID_RESPONSE",
            "message": "SpeechletResponse was null"
        },
        "cause": {
            "requestId": "..."
        },
        "type": "System.ExceptionEncountered",
        "requestId": "...",
        "locale": "en-US",
        "timestamp": "2017-04-16T19:05:20Z"
    }
}
```

According to this article, the issue is that Alexa expects an empty JSON response instead of null: [System Error "SpeechletResponse was null"](https://forums.developer.amazon.com/questions/49211/system-error-speechletresponse-was-null.html)

**Comment by bjorg** [comment]
For now, I'm opting for `null` and just ignore the exception, but I'd prefer if there was a way to avoid these warnings. Suggestions welcome!

**Comment by timheuer** [comment]
It expects a blank response?  I'm trying to understand what request being sent would generate that...the above indicates a request, but that looks like a response?

**Comment by bjorg** [comment]
The `System.ExceptionEncountered` request is sent after an invalid response was returned by the lambda function. 

For example, my code currently returns `null` when it receives a `PlaybackStopped`. That's the closest approximation I can do, as `PlaybackStopped` [doesn't allow a response](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference#valid-response-types-2). However, `null` is not valid and instead, it seems that Amazon expects the skill to return `{}` instead.

Does my explanation make sense?

For context, here's what I'm seeing in the CloudWatch logs:

First, I get the `PlaybackStopped` request to which the code returns `null` as response.
```
{
    "token": "ea216d56f567736706ac72c3702a3c25",
    "offsetInMilliseconds": "39471",
    "error": null,
    "currentPlaybackState": null,
    "enqueuedToken": null,
    "HasEnqueuedItem": false,
    "AudioRequestType": 2,
    "type": "AudioPlayer.PlaybackStopped",
    "requestId": "...",
    "locale": "en-US",
    "timestamp": "2017-04-18T05:16:42Z"
}
```

Then, moments later, I see the `System.ExceptionEncountered` request I pasted above.

**Comment by adriangodong** [comment]
Sending null or empty object (and thus getting the SystemException request) means Alexa does not send the expected built-in intents (e.g. `AMAZON.PauseIntent`, `AMAZON.ResumeIntent`). I've created the following response and it works:

```
new SkillResponse
{
    Version = "1.0",
    SessionAttributes = new Dictionary<string, object>(),
    Response = new ResponseBody()
    {
        ShouldEndSession = true
    }
}
```

I've created a pull request to incorporate this into the `ResponseBuilder`.

**Comment by jaddie** [comment]
Am I right in thinking this issue is dealt with and can be closed?
