### ISSUE TITLE
One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotificatio

### ISSUE THREAD

**Issue by ourweb4** [timheuer/alexa-skills-dotnet#172]
Line 42:  string countryRequested =   intentRequest?.Intent?.Slots["Country"].Value;
               

One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at LambdaAlexa.Function.FunctionHandler(SkillRequest input, ILambdaContext context) in D:\vcprojects\LambdaAlexa\LambdaAlexa\Function.cs:line 42
One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at LambdaAlexa.Function.FunctionHandler(SkillRequest input, ILambdaContext context) in D:\vcprojects\LambdaAlexa\LambdaAlexa\Function.cs:line 42

**Comment by stoiveyp** [comment]
Either intentRequest is null or your slot name is possibly not correct. If you set the lambda environment variable `LAMBDA_NET_SERIALIZER_DEBUG` to true on your lambda - you'll see the request logged in cloudwatch and you can find out where the problem is

**Comment by ourweb4** [comment]
If it is null why isn't null        thus no error?? It was working 2 mos ago...

**Comment by stoiveyp** [comment]
@ourweb4 my guess is there isn't a "Country" slot being sent in the skill request - which would cause an exception in your line of code, not a null value. without looking at the JSON being sent to your skill we can't know for sure.

If you can capture the request JSON we can see for sure.

**Comment by ourweb4** [comment]
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "country info",
            "intents": [
                {
                    "name": "AMAZON.FallbackIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                },
                {
                    "name": "CountryInfo",
                    "slots": [
                        {
                            "name": "Country",
                            "type": "AMAZON.Country"
                        }
                    ],
                    "samples": [
                        "CountryInfoIntent the capitol of {Country}",
                        "CountryInfoIntent get the capitol of {Country}",
                        "CountryInfoIntent country info for {Country}",
                        "CountryInfoIntent what is the capitol of {Country}",
                        "CountryInfoIntent about {Country}",
                        "CountryInfoIntent {Country}",
                        "CountryInfoIntent tell me the capitol of {Country}"
                    ]
                }
            ],
            "types": []
        }
    }
}

**Comment by stoiveyp** [comment]
@ourweb4 - that's the invocation model, not the request being made to your Lambda. You would need to show me a failing request for me to be able to help.

Regardless the possible options are limited, and most likely you're receiving a CountryInfo intent, with no value in the Country Slot.

Slots are not guaranteed by default, they just aid the machine learning in modelling what to look for as most likely values.

If you want a guaranteed value, I would suggest updating your skill to use Slot Validation - which you can find out about here:

https://developer.amazon.com/docs/custom-skills/validate-slot-values.html

Hope this helps

**Comment by ourweb4** [comment]
Do you    mea n the Lambda    logs?

**Comment by stoiveyp** [comment]
If you're talking about the request I said was needed for debugging  - then I don't mean all the lambda logs, but one of your requests in the logs would have caused the error you're seeing, and that's the request that should help figure out how you got the null value.

Again - I would still recommend Slot Validation if you absolutely have to have a value before your lambda gets invoked.

**Comment by ourweb4** [comment]
I tried the slot validation and it is still not working. Is there a way that I can give you all my codes? . You can look at it please and thank you. Bill

**Comment by ourweb4** [comment]
2019-10-03 15:45:40
START RequestId: f3299b72-8ef6-4d29-969c-e07c07be7310 Version: $LATEST
One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at LambdaAlexa.Function.FunctionHandler(SkillRequest input, ILambdaContext context) in D:\vcprojects\LambdaAlexa\LambdaAlexa\Function.cs:line 42

END RequestId: f3299b72-8ef6-4d29-969c-e07c07be7310
REPORT RequestId: f3299b72-8ef6-4d29-969c-e07c07be7310 Duration: 4737.54 ms Billed Duration: 4800 ms Memory Size: 128 MB Max Memory Used: 78 MB Init Duration: 219.25 ms
START RequestId: 534f52d6-6cad-40aa-911e-71450784fa37 Version: $LATEST
END RequestId: 534f52d6-6cad-40aa-911e-71450784fa37

**Comment by stoiveyp** [comment]
Hi @ourweb4 - I'm afraid between my real job and my family I don't have time to examine all your code. And, as I've said, I don't think the problem _is_ your code, but the request you're getting.

You can log the request in cloudwatch by setting an environmental variable on your lambda. the variable name is `LAMBDA_NET_SERIALIZER_DEBUG` and the value needs to be `true`

When this is on your lambda, if you make a request that fails, the JSON that your lambda got sent will appear in the Cloudwatch logs, and you can see the whole request - not just the error.

Without that there's not much more we can do I'm afraid.

Thanks

Steven

**Comment by ourweb4** [comment]
I logged into cloudwatch, I dont see where I set the environmental variable?

**Comment by stoiveyp** [comment]
You set the environmental variable on the lambda - there's an environmental variable section where it can be placed.

After you've saved the change to the lambda, you need to cause the failure, and then the skillrequest JSON will appear in Cloudwatch.

**Comment by ourweb4** [comment]
Lambda Deserialize Alexa.NET.Request.SkillRequest:
{
    "version": "1.0",
    "session": {
        "new": true,
        "sessionId": "amzn1.echo-api.session.84d287c3-ddad-4074-ad8d-09305203ff62",
        "application": {
            "applicationId": "amzn1.ask.skill.da314f62-eeca-48b7-9ce3-563555e1a433"
        },
        "user": {
            "userId": "amzn1.ask.account.AHNFKTIGJTP3AVJE6A4AIUYCN2RQRGCL52BIKDX4IYL6Z7R6D7NPQRZN54VQAPZNMWI2VRH6DPFAQCXOTPYR2VO36H5YKCIA72E3FNOSXNPIK4QJAZZJ3RK6BXKAUZM7KH6UU5KQE27IBOLNICV7HVU2MBYJQILYXKLPVJMLIHYRURIJH263N2MRQR37BBHMIROFNACWGGHIGTY"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.da314f62-eeca-48b7-9ce3-563555e1a433"
            },
            "user": {
                "userId": "amzn1.ask.account.AHNFKTIGJTP3AVJE6A4AIUYCN2RQRGCL52BIKDX4IYL6Z7R6D7NPQRZN54VQAPZNMWI2VRH6DPFAQCXOTPYR2VO36H5YKCIA72E3FNOSXNPIK4QJAZZJ3RK6BXKAUZM7KH6UU5KQE27IBOLNICV7HVU2MBYJQILYXKLPVJMLIHYRURIJH263N2MRQR37BBHMIROFNACWGGHIGTY"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AFHPF4C56JOIS475G5L6F57BZKCWUX5DORXTGE3G4G5YO344IUV6X3TURCOMJ3E7KFCBMKOYK3DGTX3LVGZ2TZP5ULZPBTAUI3KYRMO7LK4CLEIPTIZF3EK5XIU36BFOZJSUI4Z4JDSQRSSXUFWI6MYJPJ7HTQDPDZ5BHSAL243PKECLOQWRY",
                "supportedInterfaces": {}
            },
            "apiEndpoint": "https://api.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmRhMzE0ZjYyLWVlY2EtNDhiNy05Y2UzLTU2MzU1NWUxYTQzMyIsImV4cCI6MTU3MDEyOTIwOSwiaWF0IjoxNTcwMTI4OTA5LCJuYmYiOjE1NzAxMjg5MDksInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQUFCZ2haYXVidHorK1B5WjZvWVJvRkZtS2dFQUFBQUFBQURoMll6UE5oSENYS3hURURnL2d3cllTU2s5ZnU3aGJsQmxaVHNpK0gyZGVON1p3VzNhSXp5OFAvTlJRR0Y5MjhSUk43RXlucFRQNzRzaEQ4RXllRlhSK09nQnNKOVUrNDlKYkU1NTV1Vk9Na0I3KzhvUGQ2Z2tKTytZMU8yb203Qkx5d2JvTTY5S1p6cWc2aU4xREx6NVJrYnFOYWVmS1RpZ0JGbE5iZVZnbDR5ays3YVptb2hPVThiZjYxVnhyb0U0R2ZoUUtNK0RaLy80aDFkMEVSTndENVdNYmVZS1ArZDMrbExlY1RPSGNGVHRROVI5VThxMU1lVjNKeWIraC9wVS9qMU8rZFdhT1dDa2J4bUE0bDhmK1d2VlR4MlBNL2pKUmszOExLeE9pNnVPWTU3aE5McmlyVlpDRWQ3ZTFESTBreHVMVWtnRVRiMDJ4aElEcmZMK3ZpWEpUbXltS21kVDZLSWh4Q3VzMXVlcHRzOHl2RHNneEZzQjVyUmlDbDFwazZlRGwzcXZ5R2hSIiwiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZIUEY0QzU2Sk9JUzQ3NUc1TDZGNTdCWktDV1VYNURPUlhUR0UzRzRHNVlPMzQ0SVVWNlgzVFVSQ09NSjNFN0tGQ0JNS09ZSzNER1RYM0xWR1oyVFpQNVVMWlBCVEFVSTNLWVJNTzdMSzRDTEVJUFRJWkYzRUs1WElVMzZCRk9aSlNVSTRaNEpEU1FSU1NYVUZXSTZNWUpQSjdIVFFEUERaNUJIU0FMMjQzUEtFQ0xPUVdSWSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFITkZLVElHSlRQM0FWSkU2QTRBSVVZQ04yUlFSR0NMNTJCSUtEWDRJWUw2WjdSNkQ3TlBRUlpONTRWUUFQWk5NV0kyVlJINkRQRkFRQ1hPVFBZUjJWTzM2SDVZS0NJQTcyRTNGTk9TWE5QSUs0UUpBWlpKM1JLNkJYS0FVWk03S0g2VVU1S1FFMjdJQk9MTklDVjdIVlUyTUJZSlFJTFlYS0xQVkpNTElIWVJVUklKSDI2M04yTVJRUjM3QkJITUlST0ZOQUNXR0dISUdUWSJ9fQ.dosUW5Y9tYSdhCjwFprzM0TgNvjCXE7DyvZVRPEfwvBm9ny-_oxySWSBUTPw2-va059Qa1pYOx_RKKoUm0VI7N6KPAa4MCuaY_zLDLK0foscB_cl1Nq0iTA48w18ZEHUXZzSBP1OH-6YK2P_7cbtvj-TgZFRHX1elbjxRQs3ukhiV5I3bqvxzlH4_JYWxwTIcs5gA0Z41bKAXU7QL7jhcF7IGLQ9e77nD6nQzmX41eGGlwvm4rGv9k1r1o-7GHZ4ZDh273VmzERnKzmJp7k90eSByPEYzweHmLLKn92ICdeUMxKpmRSqKe_DXgiEG9BytUVyv1UZoVJny2o3cSc3Rw"
        }
    },
    "request": {
        "type": "IntentRequest",
        "requestId": "amzn1.echo-api.request.37ecf7ac-c052-48a6-99b3-d50d1b7adde1",
        "timestamp": "2019-10-03T18:55:09Z",
        "locale": "en-US",
        "intent": {
            "name": "AMAZON.FallbackIntent",
            "confirmationStatus": "NONE"
        }
    }
}Lambda Deserialize Alexa.NET.Request.SkillRequest:
{
    "version": "1.0",
    "session": {
        "new": true,
        "sessionId": "amzn1.echo-api.session.84d287c3-ddad-4074-ad8d-09305203ff62",
        "application": {
            "applicationId": "amzn1.ask.skill.da314f62-eeca-48b7-9ce3-563555e1a433"
        },
        "user": {
            "userId": "amzn1.ask.account.AHNFKTIGJTP3AVJE6A4AIUYCN2RQRGCL52BIKDX4IYL6Z7R6D7NPQRZN54VQAPZNMWI2VRH6DPFAQCXOTPYR2VO36H5YKCIA72E3FNOSXNPIK4QJAZZJ3RK6BXKAUZM7KH6UU5KQE27IBOLNICV7HVU2MBYJQILYXKLPVJMLIHYRURIJH263N2MRQR37BBHMIROFNACWGGHIGTY"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.da314f62-eeca-48b7-9ce3-563555e1a433"
            },
            "user": {
                "userId": "amzn1.ask.account.AHNFKTIGJTP3AVJE6A4AIUYCN2RQRGCL52BIKDX4IYL6Z7R6D7NPQRZN54VQAPZNMWI2VRH6DPFAQCXOTPYR2VO36H5YKCIA72E3FNOSXNPIK4QJAZZJ3RK6BXKAUZM7KH6UU5KQE27IBOLNICV7HVU2MBYJQILYXKLPVJMLIHYRURIJH263N2MRQR37BBHMIROFNACWGGHIGTY"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AFHPF4C56JOIS475G5L6F57BZKCWUX5DORXTGE3G4G5YO344IUV6X3TURCOMJ3E7KFCBMKOYK3DGTX3LVGZ2TZP5ULZPBTAUI3KYRMO7LK4CLEIPTIZF3EK5XIU36BFOZJSUI4Z4JDSQRSSXUFWI6MYJPJ7HTQDPDZ5BHSAL243PKECLOQWRY",
                "supportedInterfaces": {}
            },
            "apiEndpoint": "https://api.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmRhMzE0ZjYyLWVlY2EtNDhiNy05Y2UzLTU2MzU1NWUxYTQzMyIsImV4cCI6MTU3MDEyOTIwOSwiaWF0IjoxNTcwMTI4OTA5LCJuYmYiOjE1NzAxMjg5MDksInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQUFCZ2haYXVidHorK1B5WjZvWVJvRkZtS2dFQUFBQUFBQURoMll6UE5oSENYS3hURURnL2d3cllTU2s5ZnU3aGJsQmxaVHNpK0gyZGVON1p3VzNhSXp5OFAvTlJRR0Y5MjhSUk43RXlucFRQNzRzaEQ4RXllRlhSK09nQnNKOVUrNDlKYkU1NTV1Vk9Na0I3KzhvUGQ2Z2tKTytZMU8yb203Qkx5d2JvTTY5S1p6cWc2aU4xREx6NVJrYnFOYWVmS1RpZ0JGbE5iZVZnbDR5ays3YVptb2hPVThiZjYxVnhyb0U0R2ZoUUtNK0RaLy80aDFkMEVSTndENVdNYmVZS1ArZDMrbExlY1RPSGNGVHRROVI5VThxMU1lVjNKeWIraC9wVS9qMU8rZFdhT1dDa2J4bUE0bDhmK1d2VlR4MlBNL2pKUmszOExLeE9pNnVPWTU3aE5McmlyVlpDRWQ3ZTFESTBreHVMVWtnRVRiMDJ4aElEcmZMK3ZpWEpUbXltS21kVDZLSWh4Q3VzMXVlcHRzOHl2RHNneEZzQjVyUmlDbDFwazZlRGwzcXZ5R2hSIiwiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUZIUEY0QzU2Sk9JUzQ3NUc1TDZGNTdCWktDV1VYNURPUlhUR0UzRzRHNVlPMzQ0SVVWNlgzVFVSQ09NSjNFN0tGQ0JNS09ZSzNER1RYM0xWR1oyVFpQNVVMWlBCVEFVSTNLWVJNTzdMSzRDTEVJUFRJWkYzRUs1WElVMzZCRk9aSlNVSTRaNEpEU1FSU1NYVUZXSTZNWUpQSjdIVFFEUERaNUJIU0FMMjQzUEtFQ0xPUVdSWSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFITkZLVElHSlRQM0FWSkU2QTRBSVVZQ04yUlFSR0NMNTJCSUtEWDRJWUw2WjdSNkQ3TlBRUlpONTRWUUFQWk5NV0kyVlJINkRQRkFRQ1hPVFBZUjJWTzM2SDVZS0NJQTcyRTNGTk9TWE5QSUs0UUpBWlpKM1JLNkJYS0FVWk03S0g2VVU1S1FFMjdJQk9MTklDVjdIVlUyTUJZSlFJTFlYS0xQVkpNTElIWVJVUklKSDI2M04yTVJRUjM3QkJITUlST0ZOQUNXR0dISUdUWSJ9fQ.dosUW5Y9tYSdhCjwFprzM0TgNvjCXE7DyvZVRPEfwvBm9ny-_oxySWSBUTPw2-va059Qa1pYOx_RKKoUm0VI7N6KPAa4MCuaY_zLDLK0foscB_cl1Nq0iTA48w18ZEHUXZzSBP1OH-6YK2P_7cbtvj-TgZFRHX1elbjxRQs3ukhiV5I3bqvxzlH4_JYWxwTIcs5gA0Z41bKAXU7QL7jhcF7IGLQ9e77nD6nQzmX41eGGlwvm4rGv9k1r1o-7GHZ4ZDh273VmzERnKzmJp7k90eSByPEYzweHmLLKn92ICdeUMxKpmRSqKe_DXgiEG9BytUVyv1UZoVJny2o3cSc3Rw"
        }
    },
    "request": {
        "type": "IntentRequest",
        "requestId": "amzn1.echo-api.request.37ecf7ac-c052-48a6-99b3-d50d1b7adde1",
        "timestamp": "2019-10-03T18:55:09Z",
        "locale": "en-US",
        "intent": {
            "name": "AMAZON.FallbackIntent",
            "confirmationStatus": "NONE"
        }
    }
}

**Comment by stoiveyp** [comment]
Okay so @ourweb4 - can you please delete that message, those tokens are live and will allow people to act as your skill.

What you can see though is that you're getting `AMAZON.FallbackIntent` - which is what you receive when what the user has says doesn't match any of your intents. So there are no slots, which mean your code will break if it assumes the slot value exists.

What you need is to ensure you only run your code when it's your `Country` intent that's been invoked. Something like `if(intentRequest.Intent.Name == 'Country')` or whatever works for your skill

Hope this helps

**Comment by timheuer** [comment]
Removed comment w api data

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tushar5292** [comment]
**Hi I wrote below lambda fuction in C#👍** 

 public async Task<APIGatewayProxyResponse> fnGetUserLoginTest(SSUsers user, ILambdaContext context)
        {
            Amazon.DynamoDBv2.AmazonDynamoDBConfig amazonDynamoDBConfig = new Amazon.DynamoDBv2.AmazonDynamoDBConfig { RegionEndpoint = RegionEndpoint.USEast2 };
            Amazon.DynamoDBv2.AmazonDynamoDBClient client = new Amazon.DynamoDBv2.AmazonDynamoDBClient(amazonDynamoDBConfig);
            Table myTable = Table.LoadTable(client, "Serena_Users");
            ScanFilter scanFilter = new ScanFilter();
            scanFilter.AddCondition("Id", ScanOperator.In, user.Id); //Whatever your filter is
            scanFilter.AddCondition("Password", ScanOperator.In, user.Password); //Whatever your filter is
            Search search = myTable.Scan(scanFilter);
            //List<dynamic> docList = new List<dynamic>();
            var docList = await search.GetNextSetAsync();

            var response = new APIGatewayProxyResponse
            {
                StatusCode = (int)HttpStatusCode.OK,
                Body = JsonConvert.SerializeObject(docList),
                Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
            };
            return response;

}
I sent **request** as 

{
    "Id": "Test02@xyz.com",
    "Password": "Test02@xyz"
}

****In **response** after genrating API i am getting below error-** Internal Server Error**


One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.AttributeValueMarshaller.Marshall(AttributeValue requestObject, JsonMarshallerContext context)
   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.ConditionMarshaller.Marshall(Condition requestObject, JsonMarshallerContext context)
   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.ScanRequestMarshaller.Marshall(ScanRequest publicRequest)
   at Amazon.Runtime.Internal.Marshaller.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.DynamoDBv2.DocumentModel.Search.GetNextSetHelperAsync(CancellationToken cancellationToken)
   at AWSLambdaFunction.Function.fnGetUserLoginTest(SSUsers user, ILambdaContext context) in C:\Users\archa\source\repos\AWSLambdaFunction\AWSLambdaFunction\Function.cs:line 296

**Comment by stoiveyp** [comment]
Hi @Tushar5292 - don't know your context but assuming your dynamo information is correct I would imagine there's a problem with the SSUsers object being deserialized. I'd put some `string.IsNullOrWhitespace` checks at the top of the method and see if one of them isn't being set correctly.

Hope you fix it - if your code gets to use our library we'll definitely be able to help you out more 👍

**Comment by Tushar5292** [comment]
**@stoiveyp  - I want to get single record from dynamodb and display it in reponse.I am stuck with lambda response problem.If you could provide me some help then life is easy for me.**

In request I have send 2 string parameters and I want to get its record from user table by pssing those 2 params.

I am facing issue by using below code 

public async Task fnGetUserLoginTest(SSUsers user, ILambdaContext context)
{
Amazon.DynamoDBv2.AmazonDynamoDBConfig amazonDynamoDBConfig = new Amazon.DynamoDBv2.AmazonDynamoDBConfig { RegionEndpoint = RegionEndpoint.USEast2 };
Amazon.DynamoDBv2.AmazonDynamoDBClient client = new Amazon.DynamoDBv2.AmazonDynamoDBClient(amazonDynamoDBConfig);
Table myTable = Table.LoadTable(client, "User");
ScanFilter scanFilter = new ScanFilter();
scanFilter.AddCondition("Id", ScanOperator.In, user.Id); //Whatever your filter is
scanFilter.AddCondition("Password", ScanOperator.In, user.Password); //Whatever your filter is
Search search = myTable.Scan(scanFilter);
//List docList = new List();
var docList = await search.GetNextSetAsync();

        var response = new APIGatewayProxyResponse
        {
            StatusCode = (int)HttpStatusCode.OK,
            Body = JsonConvert.SerializeObject(docList),
            Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
        };
        return response;
}

**Comment by Tushar5292** [comment]
@stoiveyp 
dynamoDbClient.GetItemAsync using for getting single record from dynamo db.
but after aws lambda publish it is throwing syntax error.

 public async Task<string> GetPlaceDetailsFunction(string Place)
        {
            var dynamoDbClient = new AmazonDynamoDBClient(
            new BasicAWSCredentials(_accessKey, _secretKey),
            new AmazonDynamoDBConfig
            {
                ServiceURL = "https://dynamodb.us-east-2.amazonaws.com",
                RegionEndpoint = RegionEndpoint.USEast2
            });
            Dictionary<string, AttributeValue> item = (await **dynamoDbClient.GetItemAsync**(new GetItemRequest
            {
                TableName = "Places",
                ConsistentRead = true,
                Key = new Dictionary<string, AttributeValue>
                {
                    { "PlaceName", new AttributeValue{S=Place } },
                }
            })).Item;
            var call = item.Values;

            return JsonConvert.SerializeObject(call, Formatting.Indented);

 
        }

**Comment by Tushar5292** [comment]
@stoiveyp  I want to get a single record from dynamo db table using aws lambda functionpassing 2 params in req .What code i need to use.
Please let me know i am stuck .I am new to it so bit confuse.

**Comment by Tushar5292** [comment]
@stoiveyp I am using below code to retrieve data from registration table and sending APIGatewayProxyResponse -  Task<string>  after deployment of API using this below function it is sending me this error - **One or more errors occurred. (Supplied AttributeValue is empty, must contain exactly one of the supported datatypes): AggregateException
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal** 

Request 👍SSUsers 
 {
  "Id": "TestG@abc.com",
  "Password": "TestG1234"
}

Function I wrote :
public async Task<APIGatewayProxyResponse> fn_GetRegisteredUserFormat(SSUsers user, ILambdaContext context)
        {
            Console.WriteLine("Execution started for function -  {0} at {1}",
                          context.FunctionName, DateTime.Now);

            var dynamoDbClient = new AmazonDynamoDBClient(
            new BasicAWSCredentials(_accessKey, _secretKey),
            new AmazonDynamoDBConfig
            {
                ServiceURL = "https://dynamodb.us-east-2.amazonaws.com",
                RegionEndpoint = RegionEndpoint.USEast2
            });

            Dictionary<string, AttributeValue> registration = (await dynamoDbClient.GetItemAsync(new GetItemRequest
            {
                TableName = "Registration",
                ConsistentRead = true,
                Key = new Dictionary<string, AttributeValue>
                {
                    { "Id", new AttributeValue { S = user.Id } }
                }
            })).Item;

            string reqID = registration["Id"].S;
            string reqPass = registration["Password"].S;
            //string fresult = "[{\"Id\":{\"Value\":\""+ reqID+"\",\"Type\":0}}]";
             
            string sresult = "Id:" + reqID + "Password:" + reqPass;

            Task<string> t = Task.Run(() =>
            {
                return reqID;
            });

            context.Logger.Log("Id:" + reqID);
            context.Logger.Log("Password:" + t.Result);
           

            if (reqID == user.Id || reqPass == user.Password)
            {
                var response = new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.OK,
                    **Body = t.Result != null ? JsonConvert.SerializeObject(t.Result) : string.Empty,**
                    Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
                };

                return response;
            }
            else
            {
                var response = new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.BadRequest,
                    Body = string.Empty,
                    Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
                };

                return response;
            }
        }

I want to **getitembyid** from dynamo db using lambda function.

**Comment by Tushar5292** [comment]
@stoiveyp I am using below code to retrieve data from registration table and sending APIGatewayProxyResponse -  Task<string>  after deployment of API using this below function it is sending me this error - **One or more errors occurred. (Supplied AttributeValue is empty, must contain exactly one of the supported datatypes): AggregateException
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal** 

Request 👍SSUsers 
 {
  "Id": "TestG@abc.com",
  "Password": "TestG1234"
}

Function I wrote :
public async Task<APIGatewayProxyResponse> fn_GetRegisteredUserFormat(SSUsers user, ILambdaContext context)
        {
            Console.WriteLine("Execution started for function -  {0} at {1}",
                          context.FunctionName, DateTime.Now);

            var dynamoDbClient = new AmazonDynamoDBClient(
            new BasicAWSCredentials(_accessKey, _secretKey),
            new AmazonDynamoDBConfig
            {
                ServiceURL = "https://dynamodb.us-east-2.amazonaws.com",

                RegionEndpoint = RegionEndpoint.USEast2
            });

            Dictionary<string, AttributeValue> registration = (await dynamoDbClient.GetItemAsync(new GetItemRequest
            {
                TableName = "Registration",
                ConsistentRead = true,
                Key = new Dictionary<string, AttributeValue>
                {
                    { "Id", new AttributeValue { S = user.Id } }
                }
            })).Item;

            string reqID = registration["Id"].S;
            string reqPass = registration["Password"].S;
            //string fresult = "[{\"Id\":{\"Value\":\""+ reqID+"\",\"Type\":0}}]";
             
            string sresult = "Id:" + reqID + "Password:" + reqPass;

            Task<string> t = Task.Run(() =>
            {
                return reqID;
            });

            context.Logger.Log("Id:" + reqID);
            context.Logger.Log("Password:" + t.Result);
           

            if (reqID == user.Id || reqPass == user.Password)
            {
                var response = new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.OK,
                    **Body = t.Result != null ? JsonConvert.SerializeObject(t.Result) : string.Empty,**
                    Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
                };

                return response;
            }
            else
            {
                var response = new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.BadRequest,
                    Body = string.Empty,
                    Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
                };

                return response;
            }
        }

I want to **getitembyid** from dynamo db using lambda function
