### ISSUE TITLE
CreateResponse return SkillResponse with NULL Content can cause "INVALID_RESPONSE" "SpeechletResponse was null"

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [timheuer/alexa-skills-dotnet#173]
Hi,

Please be free to say this is a .NET issue, but with latest VS 16.3.2 and updated Nuget packages for Alexa.NET and Azure functions 1 and 2 I get "SessionEndedRequest" with error "INVALID_RESPONSE" "SpeechletResponse was null"... but ONLY with Azure Functions 1 (.NET Framework).

This used to work and I have too many variables changed to tie it down but basically, a Azure Functions 2 removes the NULLS from the response in the code below, but the Azure Function 1 maintains the NULLS e.g. image below extract from NGrok (open it to see full content)

If I use the commented out code, to remove NULLs and pass as a string of json all is fine with Amazon. Or somehow in Azure Functions 2 (.net core) that happens anyway.

![image](https://user-images.githubusercontent.com/22054739/66338463-14083280-e939-11e9-82b3-f5b27c48ea16.png)

```
            string requestBody = new StreamReader(await req.Content.ReadAsStreamAsync()).ReadToEnd();
            SkillRequest skillRequest = JsonConvert.DeserializeObject<SkillRequest>(requestBody);

            SkillResponse response1 = null; // new SkillResponse();
            response1 = ResponseBuilder.Tell("This is the response");

            response1.Response.ShouldEndSession = true;

            String szResponseNoNull = JsonConvert.SerializeObject(response1, Newtonsoft.Json.Formatting.None,
                                        new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });

            // return req.CreateResponse(System.Net.HttpStatusCode.OK, szResponseNoNull);
            return req.CreateResponse(System.Net.HttpStatusCode.OK, response1);

```

**Comment by stoiveyp** [comment]
@Crispin-at-Linknode I believe we've seen this before and it's because azure functions don't rely on JSON.Net for serialization - you shouldn't need to use such verbose code as we place NullValueHandling in our attributes. Just `JsonConvert.SerializeObject(response1)` should do the trick.
