### ISSUE TITLE
Cannot get and set SESSION Vars

### ISSUE THREAD

**Issue by pavll** [timheuer/alexa-skills-dotnet#174]
I set the Var:
`SkillResponse response = null;
session.Attributes.Add("game_mode", 2);

                                response = AlexaSkillHandler.GetDifficultyQuestion("Text <prosody rate=\"slow\">Text</prosody>!", session);
return new OkObjectResult(response);`

And if i try to get the attr from the Session when the next handler gets called:
`object gameMode;
                        session.Attributes.TryGetValue("game_mode", out gameMode);
switch (int.Parse(gameMode as string))
                                {
                                    case 0:
                                        if (!session.Attributes.ContainsKey("asked_country_questions"))
                                            session.Attributes["asked_co_questions"] = new int[] { 99 };
                                        response = CreateLQuestion(session);
                                        break;
                                    case 1:
                                        if (!session.Attributes.ContainsKey("asked_city_questions"))
                                            session.Attributes["asked_c_questions"] = new int[] { 99 };
                                        response = CreateSQuestion(session);
                                        break;
                                    case 2:
                                        // TODO: BQuestions !!!!!!!!!!!!!!!!!!!!!!!!!!!!
                                        if (!session.Attributes.ContainsKey("asked_building_questions"))
                                            session.Attributes["asked_c_questions"] = new int[] { 99 };
                                        response = CreateSQuestion(session);
                                        break;
                                    default: break;
                                }`
But even if i try to get the attr: Executed 'AlexaSkillHandler' (Failed, Id=e5f440b1-9f6a-421d-8fbc-f6b73aa0d3e0)
[19.10.2019 11:34:14] System.Private.CoreLib: Exception while executing function: AlexaSkillHandler. System.Private.CoreLib: Value cannot be null.
[19.10.2019 11:34:14] Parameter name: s.

**Comment by stoiveyp** [comment]
Hi @pavll - first of all are you running theatest version? Integer session values had a problem a while back.

Assuming you are could you show the code that actually generates the response and request objects? We need to see the Alexa.NET code that you use inside `GetDifficultyQuestion` and how you get your Alexa request object deserialized.

The reason I ask is to ensure the session is being set properly and the request is deserialized properly from JSON.Net - thank you
