### ISSUE TITLE
permissions contains invalid permission on AskForPermissionsConsentCard()

### ISSUE THREAD

**Issue by harrypotter06** [timheuer/alexa-skills-dotnet#175]
Hello,

for AskForPermissionsConsentCard() we got an Error Message:
permissions contains invalid permission

We need simple Card for AkskForPermission and use this code:

AskForPermissionsConsentCard actual = new AskForPermissionsConsentCard();
actual.Permissions.Add("alexa::profile:email:read");
response.Response.Card = actual;
                        
The Skill has only permission to email, but other informations are not need.
Any solutions or is this function missing?

**Comment by stoiveyp** [comment]
Hi @harrypotter06 - card syntax is okay. This normally means you've not enabled the permission in the skill console. Can you please confirm the email permission is enabled in the permissions tab of the Alexa skill?

**Comment by harrypotter06** [comment]
Hi Sven,

> Hi @harrypotter06 - card syntax is okay. This normally means you've not enabled the permission in the skill console. Can you please confirm the email permission is enabled in the permissions tab of the Alexa skill?

Hi Sven,

yes the skill have permission to e-mail.
![image](https://user-images.githubusercontent.com/11202949/67251401-53716b80-f46f-11e9-9653-149da9c0c48c.png)

Thanks
Klaus

**Comment by stoiveyp** [comment]
I've just added this code to my test skill (I changed it so email was the only permission)
```
            var response = ResponseBuilder.Ask(_launchText, new Reprompt(Reprompt));
            response.Response.Card = new AskForPermissionsConsentCard
            {
                Permissions = new List<string> {"alexa::profile:email:read"}
            };
            return response;
```
it produced the following JSON when I ran it in the test console and the card appeared in my Alexa app as expected.
```
"card": {
  "type": "AskForPermissionsConsent",
  "permissions": [
    "alexa::profile:email:read"
  ]
}
```
Can you please confirm your card output looks the same.

**Comment by harrypotter06** [comment]
> I've just added this code to my test skill (I changed it so email was the only permission)
> 
> ```
>             var response = ResponseBuilder.Ask(_launchText, new Reprompt(Reprompt));
>             response.Response.Card = new AskForPermissionsConsentCard
>             {
>                 Permissions = new List<string> {"alexa::profile:email:read"}
>             };
>             return response;
> ```
> 
> it produced the following JSON when I ran it in the test console and the card appeared in my Alexa app as expected.
> 
> ```
> "card": {
>   "type": "AskForPermissionsConsent",
>   "permissions": [
>     "alexa::profile:email:read"
>   ]
> }
> ```
> 
> Can you please confirm your card output looks the same.

Hi Steven,

Thank you for your good support. With this code, i have also this output. 
Hope that is now okay, for the Skill Cert-team ....
