### ISSUE TITLE
AlexaSkillEvent.SkillEnabled, AlexaSkillEvent.SkillDisabled

### ISSUE THREAD

**Issue by bauchschuss** [timheuer/alexa-skills-dotnet#176]
Hi,
can you please provide the events

**- AlexaSkillEvent.SkillEnabled
- AlexaSkillEvent.SkillDisabled**

as extra type instead of just converting to 'generic' SkillEventRequest?
Especially i need the SkillDisabled event for deleting data from a DynamoDB when the skill is disabled.

Best regards
Martin

**Comment by stoiveyp** [comment]
Hi @bauchschuss - I've created the PR for these two events
