### ISSUE TITLE
Validation Error : The skill end-point is not accepting valid signed requests

### ISSUE THREAD

**Issue by troops579** [timheuer/alexa-skills-dotnet#184]
I am using Alexa.Net for skill development, used RequestVerification class from this library but still  unable to find solution for  below certification error

**The skill end-point is not accepting valid signed requests**
The skill end-point is not accepting valid signed requests. Please make sure that your signature URL validation is correct.

From this link - https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-a-web-service.html#verifying-that-the-request-was-sent-by-alexa

**Anyone know how we can get rid off this error  ?**

**Comment by sadranyi** [comment]
Have you tried using ngrok and open SSL locally ?

**Comment by troops579** [comment]
No,

I am not sure about how openssl works for service hosted on our server.

Can you please share any example or steps ?

**Comment by mphacker** [comment]
Anyone figure this out?  I am running into the issue too.  Works fine for testing but won't pass certification.

**Comment by mphacker** [comment]
I found the Verify method... and implementation by following: https://github.com/timheuer/alexa-skills-dotnet/issues/114

**Comment by epsilon-rmroch** [comment]
public static async Task<X509Certificate2> GetCertificate(Uri certificatePath)
        {
            //var response = await new HttpClient().GetAsync(certificatePath);
            //var bytes = await response.Content.ReadAsByteArrayAsync();
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            byte[] certificate = null;
            using (var web = new WebClient())
            {
                certificate = web.DownloadData(certificatePath);
            }
            return new X509Certificate2(certificate);
        }

**Comment by timheuer** [comment]
@epsilon-rmroch have you looked at the discussion/links here: https://github.com/timheuer/alexa-skills-dotnet/issues/114.

--
@stoiveyp this code worked for @epsilon-rmroch prior to latest update due to not being able to use C# 8 features in his code...verification wasn't working hence his reason to add this change in GetCertificate previously.

**Comment by stoiveyp** [comment]
@timheuer I've raised #191 to allow for custom certificate download code

**Comment by troops579** [comment]
Validation Error : The skill end-point is not accepting valid signed requests 

This issue is resolved for me...I have used .net core 2.2.web api with azure account linking. 

Issue was with **class and methods...I was using [Authorize]** ....Validation error is gone after removing this...

 Hope, it helps some one.

Below is my ValidateRequest function. It is same only difference is that I replaced ReadAsAsync methods  (as it was not available with .net core 2.2)

private async Task<bool> ValidateRequest(HttpRequest request, SkillRequest skillRequest)
        {
            try
            {
                bool isValid = false;
                bool isTimestampValid = false;


                request.Headers.TryGetValue("SignatureCertChainUrl", out var signatureChainUrl);
                if (string.IsNullOrWhiteSpace(signatureChainUrl))
                {
                    return false;
                }

                Uri certUrl;
                try
                {
                    certUrl = new Uri(signatureChainUrl);
                }
                catch
                {
                    return false;
                }

                request.Headers.TryGetValue("Signature", out var signature);
                if (string.IsNullOrWhiteSpace(signature))
                {
                    return false;
                }

/* This part  is updated for .net core 2.2 */

                string body = "";

                using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
                {
                    request.Body.Position = 0;
                    body = await reader.ReadToEndAsync();
                    request.Body.Position = 0;
                }

/* This part  is updated for .net core 2.2 */

                if (string.IsNullOrWhiteSpace(body))
                {
                    return false;
                }

                isTimestampValid = RequestVerification.RequestTimestampWithinTolerance(skillRequest);
                isValid = await RequestVerification.Verify(signature, certUrl, body);
                if (!isValid || !isTimestampValid) { return false; } else { return true; }
            }
            catch
            {
                return false;
            }
        }


///Updated with API Call

//[Authorize] - DO NOT USE AS IT GIVES ERROR IN  VALIDATION ERROR
        [HttpPost]
        public async Task<IActionResult> HandleResponse([FromBody]SkillRequest skillRequest)
        {
            HttpRequest request = this.Request;

            bool isValid = await ValidateRequest(request, skillRequest);

            var requestType = skillRequest.GetRequestType();

            string authHeader = Request.Headers["Authorization"];

            if (!isValid)
            {
                return new BadRequestResult();
            }

            SkillResponse response = null;
           
            if (requestType == typeof(LaunchRequest))
            {
                response = ResponseBuilder.Tell("Welcome to My Skill");
                response.Response.ShouldEndSession = false;              
            }

            else if (requestType == typeof(IntentRequest))
            {

                var intentRequest = skillRequest.Request as IntentRequest;

				//some more intent checks......

                if (intentRequest.Intent.Name.Equals("projectStatus"))
                {
                    response = ResponseBuilder.Tell($"Some text");
                }

                if (intentRequest.Intent.Name == "AMAZON.CancelIntent")
                {
                    response = ResponseBuilder.Tell("Cancelling.");
                }

                else if (intentRequest.Intent.Name == "AMAZON.HelpIntent")
                {
                    response = ResponseBuilder.Tell("Some message");

                    response.Response.ShouldEndSession = false;

                }

                else if (intentRequest.Intent.Name == "AMAZON.StopIntent")
                {
                    response = ResponseBuilder.Tell("Bye");
                }
            }

            else if (requestType == typeof(SessionEndedRequest))
            {
                response = ResponseBuilder.Empty();
                response.Response.ShouldEndSession = true;
            }

            return new OkObjectResult(response);

        }
