### ISSUE TITLE
Any plans to switch to System.Text.Json?

### ISSUE THREAD

**Issue by evgeni-nabokov** [timheuer/alexa-skills-dotnet#189]
I guess this requires total rewrite (different attributes etc.). What are your thoughts?

**Comment by timheuer** [comment]
@evgeni-nabokov Thanks for the comment. No plans right now in a way of ‘if it isn’t broke don’t fix it’ mindset :-). I think it would take some benchmark compared for our scenario here to Eakins if it is worth the effort right now.

**Comment by stoiveyp** [comment]
I thought I'd give this a go as an intellectual exercise - see how painful it would be.

https://github.com/stoiveyp/alexa-skills-dotnet/tree/NoNewtonsoft

Like-for-like changes aside, the really big issue seems to be that the JsonConverter attribute in System.Text.Json can't be applied to interfaces - which is something we really rely on for the polymorphism. Even with custom converters applied to the serializer options it deserializes them properly, but doesn't serialize an interface properly (won't serialize the properties that are only in that specific inmplementation - only the interface definition itself)

Gonna keep at it - I enjoy the challenge - but I might try looking at the System.Text.Json source and see if I'm missing something.

**Comment by timheuer** [comment]
Nice thanks for being willing to experiment!  As I mentioned, I'm not opposed to it but would also want to think downstream (your plugins) and would they be forced to change?  

On the note on interfaces, wonder if @terrajobst knows if this is planned or perhaps a way of achieving it.

**Comment by stoiveyp** [comment]
Absolutely right that none of the extensions would be supported, even if the conversion were flawless - the core library and each extension would need to be double tagged so we could continue `netstandard2.0` with Json.Net until end of life and `netcoreapp3.0` moving forward

I've not looked into how that would work but I'm guessing extensive use of compiler switches to ensure only the right attributes were applied to every class and property? That's a lot of maintenance (or possible a single subclassed attribute that isolates and hide the compiler switch maybe? _adds to list of things to look at)

It's also the upstream issue; although I appreciate it's not exclusive - our primary use case is AWS Lambda and that's not available in a .NET 3.1 runtime flavour yet without custom layers. Also the LambdaSerializer supported by Amazon is one based on Newtonsoft - so we'd have to customise that too.

Hugely interesting to investigate though, genuinely fun :)

**Comment by randyridge** [comment]
So I just hit this... updating from netcoreapp2.2 to 3.1, by default you get System.Text.Json wired up and then you'll end up getting a runtime exception modelbinding SkillRequest, etc.  You can obviously fix with the AddNewtonsoft extension...  I went down the route of conditionally including the correct attributes, but started to lose interest with 500 remaining errors... :)

**Comment by stoiveyp** [comment]
So I don't forget, this is the issue that would allow our "converter on interface" approach to so much of the ecosystem to be supported in System.Text.Json, currently against .NET 5.0 (although there is an interesting workaround I'm going to have a play with this week in my branch) 

https://github.com/dotnet/runtime/issues/33112

**Comment by ncipollina** [comment]
> I thought I'd give this a go as an intellectual exercise - see how painful it would be.
> 
> https://github.com/stoiveyp/alexa-skills-dotnet/tree/NoNewtonsoft
> 
> Like-for-like changes aside, the really big issue seems to be that the JsonConverter attribute in System.Text.Json can't be applied to interfaces - which is something we really rely on for the polymorphism. Even with custom converters applied to the serializer options it deserializes them properly, but doesn't serialize an interface properly (won't serialize the properties that are only in that specific inmplementation - only the interface definition itself)
> 
> Gonna keep at it - I enjoy the challenge - but I might try looking at the System.Text.Json source and see if I'm missing something.

This is actually something that I have started to work on myself. I have gotten the polymorphsim working with abstract classes instead of interfaces. I managed to get the base library working and had made some very good progress on APL (as these are the only two I've been using). I have a completely seperate private repo that I've been working on, but would be willing to help out with this effort if anyone wanted to try and make it work.

**Comment by ncipollina** [comment]
If you are still looking for this, I have another repo based off of this one that has all of the objects but using System.Text.Json. You can find that [here](https://github.com/ncipollina/alexa-vox-craft).

@evgeni-nabokov

**Comment by timheuer** [comment]
I've definitely let this linger :-( -- What was the biggest problem being solved by switching to S.T.J?  my main reason has been that I don't want to introduce a change, break dependencies (given you mentioned you had to move to net8.0) and create more support for myself already on limited focus on this project :-(

**Comment by ncipollina** [comment]
I'm primarily deploying my alexa skill code to AWS Lambda, so the 2 biggest things for me are performance and package size. S.J.T. is more performant and has a much smaller footprint. Plus, theoretically you could off AOT support as well by converting. As I mentioned in my comment above, I've created a separate version of your models in a different repo that are System.Text.Json. So if you don't want to migrate/update/maintain, I can just use that version.,
