### ISSUE TITLE
Migration .NET Core 2.1 to 3.1 > parameterless constructor is not supported Type 'Alexa.NET.Request.Type.Request' 

### ISSUE THREAD

**Issue by TheDevKnight** [timheuer/alexa-skills-dotnet#193]
Hi,

i have a very simple ASP .NET Core app as custom backend for my alexa skill and it work very well as a .NET Core 2.1 version with Alexa.NET 1.5.7 . But after the migration (i created a new version as .NET Core 3.1 + Alexa.NET 1.12.0), my POST Method is not executed and i became the following error (copy from postman).

`System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported. Type 'Alexa.NET.Request.Type.Request'
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeCreateObjectDelegateIsNull(Type invalidType)
   at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 4222
Content-Type: application/json
Cookie: .AspNetCore.Antiforgery.vA5IWkIFKFs=CfDJ8KZ3LOsvjJpLps44pj961A4tlt3DMnQOpRErO6lVQ16shSQKOWHzWWbJb1mFcAOQitth0tyODoBwCmC11Jjak9TzCb4sPqbkGAhajr2LqsJwGKOz4xW_kQ3RxdIKo5jyTgNnT7yw-MjeF5Zoeju2LCE
Host: localhost:64055
User-Agent: PostmanRuntime/7.6.0
Postman-Token: 200405b3-6078-4a0e-b916-14df4330d80c
`  
The Problem is not the NuGet Alexa.NET because i can update the old ASP .NET Core app to 1.12.0 and it works. 

I use the default template and changed nothing. Here is the Startup.cs (old and new)

Old 2.1 Version
` public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
        }
    }`

New 3.1 Version
`public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }`

My Controller is very very very simple to test the Deserialization 

`    [Route("[controller]")]
    [ApiController]
    public class DefaultController : ControllerBase
    {
        [HttpGet]
        public string Test()
        {
            return "Erfolgreich!";
        }

        [HttpPost]
        public SkillResponse HandleResponse([FromBody]SkillRequest input)
        {
            return ResponseBuilder.Tell("OK", null);
        }
    }`

It looks like it is a problem of System.Text.Json withcn replace Newtonsoft in .NET CORE 3.0.
What can i do?

Regards

**Comment by TheDevKnight** [comment]
Sorry, but the Issue could be closed. I foudn the solution 5mins after the post :(

https://dotnetcoretutorials.com/2019/12/19/using-newtonsoft-json-in-net-core-3-projects/

The solution is to switch back to newtonsoft with 

`
public void ConfigureServices(IServiceCollection services)
{
      services.AddControllers().AddNewtonsoftJson();
}
`

Regards

**Comment by alexhorner** [comment]
Hi there,

Would I please be able to reipen this issue? It is still present in .NET 5 and using a third party library like Newtonsoft, whilst an acceptable solution, seems like an unnecessary one. Is there something here which can be done to fix the issue with the native JSON deserialiser?

Thanks!

**Comment by stoiveyp** [comment]
As someone who really would like to make this possible it is something I keep an eye on. Unfortunately the necessary changes for it to work out of the box with the default System.Text.Json serializer were moved out of .NET 6 (and it's still not guaranteed some of the proposed ways of working being discussed would fit our model)

I've written custom converters that can handle the work we do with types (sub-classing based on a discriminator value) for other projects, but the cost is remembering to use customised serialiser options everywhere you need them.

If we wrote the library and extensions that way we'd be asking for each project to customise serialisation anywhere it was used - maintaining a project using Alexa.NET would potentially become messy and confusing without us writing the same kind helpers that exist for JSON.NET

Because of this it still feels to me, right now at least, that it's safer to rely on Newtonsoft.

**Comment by alexhorner** [comment]
> As someone who really would like to make this possible it is something I keep an eye on. Unfortunately the necessary changes for it to work out of the box with the default System.Text.Json serializer were moved out of .NET 6 (and it's still not guaranteed some of the proposed ways of working being discussed would fit our model)
> 
> I've written custom converters that can handle the work we do with types (sub-classing based on a discriminator value) for other projects, but the cost is remembering to use customised serialiser options everywhere you need them.
> 
> If we wrote the library and extensions that way we'd be asking for each project to customise serialisation anywhere it was used - maintaining a project using Alexa.NET would potentially become messy and confusing without us writing the same kind helpers that exist for JSON.NET
> 
> Because of this it still feels to me, right now at least, that it's safer to rely on Newtonsoft.

Would it be reasonable to at least document this requirement easily visible in something like the README? It took me a little while to actually find this issue, considering it is also closed, and would likely be out of scope for search for some people

**Comment by timheuer** [comment]
@alexhorner I kept this open to track.  Where do you think the best README note would have been for you to find it? Want to make sure we put helpful info in the most helpful places :-)

**Comment by alexhorner** [comment]
> @alexhorner I kept this open to track. Where do you think the best README note would have been for you to find it? Want to make sure we put helpful info in the most helpful places :-)

I'd likely have put it under Setup or Serialization since it relates well to both, maybe with some more details on the actual exception too if appropriate.

May I also suggest something a bit more drastic? A section or something else which describes the different implementation options (for example mine being ASP.NET Core) since I had to look elsewhere at another repo which has this library as a dependency in an ASP.NET application to understand how it should be implemented
