### ISSUE TITLE
Any plans to release a Strong Named assembly?

### ISSUE THREAD

**Issue by NickEricson** [timheuer/alexa-skills-dotnet#196]
Our build process requires all assemblies we use to be strong name signed. It would be helpful if there was a nuget package available with a strong named signed version of this assembly.

**Comment by timheuer** [comment]
Re-opening as an issue with #197 and need to figure out impact to extensions.

**Comment by timheuer** [comment]
Unlisted 1.13.1 for now FYI

**Comment by NickEricson** [comment]
We can close this, we don't need it anymore. Thank you for considering.
