### ISSUE TITLE
Unable to deserialize input

### ISSUE THREAD

**Issue by ianByrne** [timheuer/alexa-skills-dotnet#203]
Hello,

I am getting this error in my Lambda function's logs when it is invoked by the test tool in the Alexa Developer Console:

> Error converting the Lambda event JSON payload to type Alexa.NET.Request.SkillRequest: Deserialization of reference types without parameterless constructor is not supported. Type 'Alexa.NET.Request.Type.Request': JsonSerializerException
>    at Amazon.Lambda.Serialization.SystemTextJson.LambdaJsonSerializer.Deserialize[T](Stream requestStream)
>    at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
> 
>    at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeCreateObjectDelegateIsNull(Type invalidType)
>    at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan1 utf8Json, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan1 utf8Json, JsonSerializerOptions options)
>    at Amazon.Lambda.Serialization.SystemTextJson.LambdaJsonSerializer.Deserialize[T](Stream requestStream)

I have the required attribute, and the method's signature follows that in the docs:

```csharp
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.LambdaJsonSerializer))]
namespace MyFunction
{
    public class Function
    {
        public SkillResponse FunctionHandler(SkillRequest input, ILambdaContext context)
        {
```

If I instead use `object` instead of `SkillRequest` for the input, I can then use `JsonConvert` to create the `SkillRequest`. But it seems to go against the point of the `LambdaSerializer` attribute

**Comment by stoiveyp** [comment]
Hi @ianByrne - as part of support for .NET Core 3.1 Amazon have changed the lambda serializer to one one based off of the new System.Text.Json namespace.

Using that value in the attribute means any library using Newtonsoft.Json - like ours - won't deserialize automatically.

You can either use Newtonsoft directly, which seems to be what you've done so far with JsonConvert, or change the serializer back to `Amazon.Lambda.Serialization.Json.JsonSerializer` which would then let you continue as expected.

Hope this helps, and apologies for any formatting or typing issues - typing on my phone.

**Comment by ianByrne** [comment]
That was exactly it, thanks - installing the `Amazon.Lambda.Serialization.Json` nuget (and uninstalling the other one) has got it working nicely now, cheers.

By the way, I also noticed in the "Setup" section of the docs, the example seems to have an old(?) version of the `SkillResponse` object that accepts a string in the constructor (this seems to no longer be the case).

```csharp
public SkillResponse FunctionHandler(SkillRequest input, ILambdaContext context)
{
    // your function logic goes here
    return new SkillResponse("OK");
}
```
