### ISSUE TITLE
Not able to get a reprompt

### ISSUE THREAD

**Issue by jporubsky** [timheuer/alexa-skills-dotnet#207]
I copied and pasted the section from the example with ssml in order to test reprompt and it returns the message fine with the date but never asks the reprompt question and she ends the interaction as soon as she finishes talking.
I have checked the finalResponse object and it shows ShouldEndSession: False.  Not sure if I'm missing another component or step.
Thanks

**Comment by stoiveyp** [comment]
Hi @jporubsky - are you able to tell us where you're testing it? That sounds like something that can happen when you test in the browser - it doesn't support all the possible scenarios so I'd like to know if you get the same issue from a device.

If it's on a device then could you show the code that generates and returns the reprompt so we can have a look?

Thank you, hope we can help

**Comment by jporubsky** [comment]
Thanks for the reply, I am testing from a device, an Echo to be specific. I'm using the code snipit from the documentation: 

`// create the speech response
var speech = new SsmlOutputSpeech();
speech.Ssml = "<speak>Today is <say-as interpret-as=\"date\">????0922</say-as>.</speak>";

// create the speech reprompt
var repromptMessage = new PlainTextOutputSpeech();
repromptMessage.Text = "Would you like to know what tomorrow is?";

// create the reprompt
var repromptBody = new Reprompt();
repromptBody.OutputSpeech = repromptMessage;

// create the response
var finalResponse = ResponseBuilder.Ask(speech, repromptBody);
return finalResponse;`

She will say the date and then immediately terminate the dialog.

**Comment by stoiveyp** [comment]
Thanks @jporubsky - at initial glance that looks like it should work. I'm at the day job at the moment but I'll definitely try this on my own devices when I'm available.

**Comment by jporubsky** [comment]
Thanks for your help but it turns out to be something I messed up on my side later in the code.
