### ISSUE TITLE
Custom Tasks

### ISSUE THREAD

**Issue by epsilon-rmroch** [timheuer/alexa-skills-dotnet#211]
Does Alexa.NET support Custom Tasks or can Custom Tasks be added? 
[Custom Tasks](https://developer.amazon.com/en-US/docs/alexa/custom-skills/understand-tasks.html)

**Comment by stoiveyp** [comment]
Hi @epsilon-rmroch, yeah we added custom tasks a while back.
So you've got `StartConnectionDirective` for invoking a task, `TaskCompletedDirective` for responding to one as well as `SkillResumedRequest` for when your skill has control returned to it.

**Comment by epsilon-rmroch** [comment]
@stoiveyp 
Thanks for the quick response!  That is great! So, can I use that to implement the Quick Link to Custom Task in my skill?
[Quick Link](https://developer.amazon.com/en-US/docs/alexa/custom-skills/create-a-quick-link-for-your-custom-task.html)

**Comment by stoiveyp** [comment]
Can't think of any reason why not; the Quick Link functionality is a specific way of invoking the skill task - those steps are mostly defining detail correctly outside of the lambda. Once you've got your task set up the functionality itself can be received and responded to with a .NET lambda and Alexa.NET 👍
