### ISSUE TITLE
Hi stoiveyp.. what is exception class to handle null values in Environment.GetEnvironmentVariable

### ISSUE THREAD

**Issue by HarshaPuppala** [timheuer/alexa-skills-dotnet#212]
I am trying to search for a variable in AWS lambda configuration from C# code..  If the variable I am searching for is not found I am seeing null exception. I want to know how to handle it.  Instead of throwing system exception I want to show custom message like "Value you are searching for is not found"  code snippet is as below

In AWS configuration file, the value is "Zwel_come"and I am trying to search this value

string SearchVariable = "wel-come"
AWSDataInfo AWSDataobj = new AWSDataInfo();
string TempUID = 'Z' + SearchVariable.Replace('-', '_');
LambdaLogger.Log("Searchnig for UID : " + TempUID);
string AWSEnivronmentDataInfo = Environment.GetEnvironmentVariable(TempUID, EnvironmentVariableTarget.Process);
         if (AWSEnivronmentDataInfo.Equals(TempUID))
            {
                LambdaLogger.Log("UID" +TempUID+ " Data Found");
                AWSUserData = JsonConvert.DeserializeObject<AWSUserlocalObject>(AWSEnivronmentDataInfo );
}
else
{
LambdaLogger.Log("No results found in AWS environment for UID: " + TempUID );
}

Instead of seeing my custom error message I am exception as below in cloud watch. How to log custom message.

One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at FindUserLambda.Function.GetUserData(SQSMessage message, ILambdaContext context)

**Comment by stoiveyp** [comment]
Hi @HarshaPuppala - Somewhere you're performing a .Wait on some async code, possibly higher up than the code you're showing us. This means the error you'll see from the Lambda is going to return an AggregateException. If you examine that error it will have an InnerExceptions property with the "real" error in it (there is a way to flatten these errors in Lambda, but I can't remember how you get that to happen)

You need to wrap the code that's causing the problem in a try...catch block so you can catch the NullReferenceException, and return a response correctly. I assume this is an Alexa skill Lambda? So maybe your code just returns null and higher up you say if the value is null you produce a different `ResponseBuilder.Tell`? Depends a lot on how you work - but it seems like you need exception handling 👍 

Hope this helps
