### ISSUE TITLE
Anyone else experiencing certification issue with Alexa.NET and Azure?

### ISSUE THREAD

**Issue by stoiveyp** [timheuer/alexa-skills-dotnet#215]
We've had feedback that the certification step for Alexa skills isn't working when the code is an Azure Function App.

Full thread can be found here: https://github.com/timheuer/alexa-skills-dotnet/pull/191

I know the RequestVerification class works if the details are valid, but apparently a try/catch around invalid details isn't helping - so if someone else has this issue and can let me know the certificate header they're being sent so I can take a deeper look it would be much appreciated.

**Comment by troops579** [comment]
Check my code at issue   #184
