### ISSUE TITLE
Certification Error - LinkAccount 

### ISSUE THREAD

**Issue by troops579** [timheuer/alexa-skills-dotnet#217]
**Any one used LinkAccount  with Alexa.NET code.  Can you send some code pointers ? I am using azure linked account.**

Below is error received at Certification level, after validations are checked sucessfully.

The skill did not deliver a LinkAccount card to home/ activity section of Alexa app, when an intent which requires authentication is invoked without linking an account.

Please note that the skill must deliver an account link card to the Alexa app in order to complete the account linking process.

For instructions on how to send an account link card, click here and for more information on Account Linking, click here.

**Comment by stoiveyp** [comment]
Hi @troops579 do you have an example of the code where you're adding the LinkAccountCard object to your response?

**Comment by troops579** [comment]
I saw TellWithLinkAccountCard in ResponseBuilder class...but not sure how this is used in actual scenario

you can see my code at #184

**Comment by stoiveyp** [comment]
Okay - so you can get your response object with a method like `ResponseBuilder.Tell()` and that will give you a SkillResponse object. From there you go `skillResponse.Response.Card = new LinkAccountCard()`, then return the skillResponse and the card should appear in the app :+1:

**Comment by troops579** [comment]
Thanks a lot for quick reply. One small query on the same...when this should be called and under which condition.

**Comment by stoiveyp** [comment]
You use the link account card when you want someone to link their third party account to your skill

So if they've tried to access functionality that required a linked account but they don't have one - you can add the card to the response and in your speech, you ask them to link the account and let them know you've placed the link in the alexa app.

**Comment by troops579** [comment]
Yes, but how we can identify user account is linked or not from code?

**Comment by stoiveyp** [comment]
https://developer.amazon.com/en-US/docs/alexa/account-linking/add-account-linking-logic-custom-skill.html#get-token

The person and user objects have an access token property

**Comment by troops579** [comment]
@stoiveyp  Can you please review this code ?

 [HttpPost]
        public async Task<IActionResult> HandleResponse([FromBody]SkillRequest skillRequest)
        {
            HttpRequest request = this.Request;
            bool isValid = await ValidateRequest(request, skillRequest);
            var requestType = skillRequest.GetRequestType();
            string authHeader = Request.Headers["Authorization"];
            SkillResponse response = null;

            **var accessToken = skillRequest.Session.User.AccessToken;

            if (accessToken == null)
            {
//Option 1
                //response = ResponseBuilder.Tell("Welcome to My Skill. To start using this skill, please visit the home section of the Alexa app and click on the link to connect with the Alexa.");
                //response.Response.Card = new LinkAccountCard();
//Option 2
                response = ResponseBuilder.TellWithLinkAccountCard("Welcome to My Skill. To start using this skill, please visit the home section of the Alexa app and click on the link to connect with the Alexa.");
                response.Response.ShouldEndSession = true;

                return Ok(response);
            }**

            if (!isValid)
            {
                return new BadRequestResult();
            }

//OTHER CODE FOR INTENTS
}
