### ISSUE TITLE
how should i use "DialogUpdateDynamicEntities" ?

### ISSUE THREAD

**Issue by albertoVieiraNeto** [timheuer/alexa-skills-dotnet#220]
hi, i'm trying to use the class DialogUpdateDynamicEntities, for some time, just to test somenthing for a new skill that i'm creating.

i've found the [test](https://github.com/timheuer/alexa-skills-dotnet/blob/afedefd6daed0911e2a9ea9caa116c77c9559ff0/Alexa.NET.Tests/DialogDirectiveTests.cs) for this class, but unfortunatly i did not clear how this should be added to the intent or/and forwaded to amazon.

can anyone give me some direction?

**Comment by stoiveyp** [comment]
Hi @albertoVieiraNeto - you add that directive to the skill response, the skill picks up the updated slot values and uses them for that session from that point.

Hope this helps
