### ISSUE TITLE
Access to skill manifest

### ISSUE THREAD

**Issue by rkalakota** [timheuer/alexa-skills-dotnet#231]
Hi everyone!

I need to be able to access the skill manifest to be able to activate the notifications

"permissions": [
      {
        "name": "alexa :: devices: all: notifications: write"
      }
    ],

but from the developer console I don't see the option. Is it possible to access this from Alexa.NET?

Thanks in advanced

**Comment by rkalakota** [comment]
I mean how to activate publications

   "publications": [
    	  {
          "eventName": "AMAZON.WeatherAlert.Activated"
        },
        {
          "eventName": "AMAZON.SportsEvent.Updated"
        },
        {
          "eventName": "AMAZON.MessageAlert.Activated"
        },

**Comment by stoiveyp** [comment]
Hi @rkalakota - thanks for reaching out.
This isn't something you can do directly with Alexa.NET, the core library handles in-skill request/response only.

There are a few options though.
If you're looking for a way specifically in .NET, then with a Login With Amazon token we support the full SMAPI via our Management extension 
https://github.com/stoiveyp/Alexa.NET.Management

You can update it from a terminal using the ASK CLI tool:
https://developer.amazon.com/en-US/docs/alexa/smapi/quick-start-alexa-skills-kit-command-line-interface.html

Or there's a really good VS Code extension which should help too:
https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/get-started-with-the-ask-toolkit-for-visual-studio-code.html

**Comment by rkalakota** [comment]
Thanks for your response but ....

Do you know how to activate "eventName": "AMAZON.MessageAlert.Activated"
from amazon developer console?

Thanks

**Comment by stoiveyp** [comment]
You can't access the manifest from the console, only the interaction model.

You have to alter the manifest using one of the available tools, and then you interact with your skill with the client ID and secret you can get from the permissions section in the build tab.
