### ISSUE TITLE
Add support for properties used in the context of Alexa Smart Properties (review PR#236)

### ISSUE THREAD

**Issue by nachawat** [timheuer/alexa-skills-dotnet#237]
Hello,

In the context of Alexa Smart Properties (e.g Alexa for Hospitality or Alexa for Residential), the request payload sent to a skill contains additional properties.

To ensure those properties are correctly deserialized, can you please review the PR https://github.com/timheuer/alexa-skills-dotnet/pull/236 ?

Objective is to provide support to the following properties into a new minor version of the Alexa.NET SDK for developers building skills in the context of Alexa Smart Properties using Alexa.NET SDK:

- `context.System.device.persistentEndpointId`
- `context.System.unit.unitId`
- `context.System.unit.persistentUnitId`

You can refer to the official [Request and Response JSON Reference](https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html) Alexa documentation for details about each above mentioned property.

Thank you
Benoit

**Comment by timheuer** [comment]
Fixed in mentioned PR
