### ISSUE TITLE
Project 1: Can't get default Handle Response signature to work using ASP.Net Core 3.1 using documented signature

### ISSUE THREAD

**Issue by SteveJCCC** [timheuer/alexa-skills-dotnet#250]
Hi Tim,
A couple of years ago (pre pandemic) I developed a version of a response handler to work with Alexa Skills DotNet.
It all worked as expected, using the signature at the time with the [FromBody] attribute.

Now, I've picked up development on an Alexa skill again, and am using .Net Core 3.1.
I'm trying to get this working as documented, but am having various issues, from the simple project not compiling, to the signature not being matched when calling from Alexa (I have another project I'll upload shortly where I have got the call to work, but using a very different method but can't get that one to speak).

Using .Net Core 3.1, I can't get the standard signature to match as provided from Alexa Skills dotnet:

public SkillResponse FunctionHandler(SkillRequest input, ILambdaContext context)
{
    // your function logic goes here
    return new SkillResponse("OK");
}

I've had to change the return line in my uploaded project (as you'll see) to get the project to compile.

When I leave in the lambda context, I get a run time error when I try to run the project:
'Coventry_Bin_Info.Controllers.AlexaIntentController.HandleResponse (Coventry Bin Info)' has more than one parameter that was specified or inferred as bound from request body. Only one parameter per action may be bound from body. Inspect the following parameters, and use 'FromQueryAttribute' to specify bound from query, 'FromRouteAttribute' to specify bound from route, and 'FromBodyAttribute' for parameters to be bound from body:
SkillRequest input
ILambdaContext context'

If I remove the second parameter: 
ILambdaContext context

when I try to invoke my skill from the Alexa developer console, my function isn't triggered and I get the error reported back:
There was a problem with the requested skill's response

How I could get it to work was by using your suggested signature instead?
What is the ILambdaContext context parameter practicallty used for?

I'm going to raise a second issue (that project will fire the function handler), but I have to throw away the context parameter and I can't get Alexa to speak back to me.

I'm using NGROK to tunnel the request to my runtime environment, and have had no issues with tunnelling the requests.

Many thanks for your assistance with this, and your work generally.
Best regards,
Steve
[Coventry Bin Info - Project 1.zip](https://github.com/timheuer/alexa-skills-dotnet/files/9534960/Coventry.Bin.Info.-.Project.1.zip)
![Packages Used](https://user-images.githubusercontent.com/113172866/189339712-28318ec9-dce5-42a1-b344-d63de1c41fb6.jpg)

**Comment by stoiveyp** [comment]
Hi @SteveJCCC 

ILambdaContext is used when an Alexa skill is hosted in an AWS Lambda project. Are you able to confirm what kind of project your skill is hosted in, as that will affect what to look for

**Comment by stoiveyp** [comment]
Thanks @SteveJCCC - think we've had this before ( see closed issue https://github.com/timheuer/alexa-skills-dotnet/issues/193 ) and it's because as of 3.1 `System.Text.Json` became the default JSON serializer, and it has to be using Newtonsoft to work.

If you keep the default methods, then you won't get a valid request and you can't send a valid response back. It would be useful to know what the experience looks like if you swap these out (i.e. does it work? and if it doesn't work - what is the updated error information you get from your debug experience? )

**Comment by SteveJCCC** [comment]
Thanks Steven,
I really appreciate your response. I’ll have a look at that on Monday and will get back to you.
Have a great weekend,
Steve

**Comment by SteveJCCC** [comment]
Hi,

I tried following the article, but Microsoft.AspNetCore.Mvc.NewtonsoftJson would not install because it’s not compatible with .Net Core 3.1.

Would it be possible for you, Tim, to have a look at the projects I’ve included and configure/change it in a way that can work?

Kind regards,
Steve

**Comment by timheuer** [comment]
@SteveJCCC you'll have to grab the right package to include which would be this one:
```
<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.29" />
```
and then you can use the `services.AddControllers().AddNewtonsoftJson();` line and compile.

**Comment by SteveJCCC** [comment]
Ahh, wonderful. Thanks so much Tim – works fine.
Thank you for your prompt and helpful replies 😊

Best,
Steve

**Comment by timheuer** [comment]
Great! Closing this one!

**Comment by SteveJCCC** [comment]
Hi Tim and Steve,

I hope you can help me. I’m using Alexa Skills Dotnet with .Net 7.

I’m trying to get Alexa to play an audio file (just within the SSML, not using the Audio Player Request).

I’ve tried all the variations of the following SSML line I can think of:

speech.Ssml = "<speak>Hello<audio source='https://s3.amazonaws.com/cdn.dabblelab.com/audio/one-small-step-for-man.mp3' /> </speak>";
response = ResponseBuilder.Tell(speech);
return response;

I tried ending Hello with the </speak> tag, various form of quotes around the source etc., and actually running the skill on a physical device. I know the mp3 file is in the correct format for Alexa, as it was used in an example by someone else demonstrating it’s use within the SSML using Python and it worked.

Can you tell me what I’m doing wrong please because I keep on butting my head against the wall and can’t figure it out?

Thanks in anticipation, and kind regards,
Steve
