### ISSUE TITLE
Project 2: Can't use parameters normally for handling the response, and can't get Alexa to talk - There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by SteveJCCC** [timheuer/alexa-skills-dotnet#251]
Hi again Tim,

Here's the second project (attached). I can get the response function to fire this way, but it doesn't accept any parameters in the normal way. Also, I can't get Alexa to talk back, but get an error instead. What am I doing wrong please?

Best regards,
Steve

[Coventry Bin Info - Project 2.zip](https://github.com/timheuer/alexa-skills-dotnet/files/9535076/Coventry.Bin.Info.-.Project.2.zip)

**Comment by stoiveyp** [comment]
Hi @SteveJCCC I can see in the code there's the following line commented out:
```csharp
//services.AddControllers().AddNewtonsoftJson();
```
Using Newtonsoft is a requirement for the skill requests and responses to work correctly - and might be the factor in both issues you've raised.

**Comment by SteveJCCC** [comment]
Hi Steven,
No, it's hasn't made any difference.

**Comment by FelipeBergmann** [comment]
Hi @SteveJCCC ,

Recently I had some difficulties working with lambda function in .NET 6 for two reasons:

- SkillRequest class: this class has an attribute called Request of type Type.Request, the class Request is abstract,  for this reason when the lambda function was receiving a request and trying to bind the body to SkillRequest it was throwing a binding exception. You can create a workaround to fix it temporarily, for example:
```
public class CustomRequest
{
    [JsonProperty("version")]
    public string Version { get; set; }

    [JsonProperty("session")]
    public Session Session { get; set; }

    [JsonProperty("context")]
    public Context Context { get; set; }

    [JsonProperty("request")]
    public AlexaSkillRequest Request { get; set; }

    public System.Type GetRequestType()
    {
        return Request?.GetType();
    }
}

[JsonConverter(typeof(RequestConverter))]
public class AlexaSkillRequest : Alexa.NET.Request.Type.Request
{
}
```
- Response serialization: To serialize the response, amazon lib is using  System.Text.Json.JsonSerializer - I still need to search for a better solution, and it's not serializing the object attributes, it's considering the interface members only. Then, the response result just contains a null OutputSpeech  object. Could you check if the SkillResponse response is serializing the OutputSpeech at SkillResponse.Response.IOutputSpeech correctly?
Again, a possible workaround solution for lambda function:
```
Newtonsoft.Json.JsonConvert.SerializeObject(response)
```

Additionally: Personally, I recommend you upload your project into a gihub repository, so we can see your code easily, if it is possible.

I hope it helps.

**Comment by stoiveyp** [comment]
@FelipeBergmann What kind of setup did you find these issues occurring? You mentioned an Amazon lib - so I'm guessing AWS Lambda? For that to work correctly you do have to change the serializer to stop using System.Text.Json and go back to Newtonsoft ( in the docs here: https://github.com/timheuer/alexa-skills-dotnet#serialization ) 

Because of the nested structures we use there are a lot of our code that has to be re-written to make the library System.Text.Json compatible, so using Newtonsoft is the recommended approach due the kind of issues you're finding.

**Comment by SteveJCCC** [comment]
Thanks Tim :-)

**Comment by FelipeBergmann** [comment]
Hi @timheuer, 
It's AWS lambda... Now I tried your suggestion to change the json serializer to newtonsoft and it worked well.

Thanks for the helping!
