### ISSUE TITLE
EmphasisLevel: Wrong value replacement

### ISSUE THREAD

**Issue by FelipeBergmann** [timheuer/alexa-skills-dotnet#252]
Hello,

I found a mismatch value on EmphasisLevel. For reduced const value it should be reduced instead of reducated. 
Docs: [developer amazon SSML](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#emphasis
)
https://github.com/timheuer/alexa-skills-dotnet/blob/6dd67c9cc38b5465a793d23c3e320d9a049fd3d9/Alexa.NET/Response/Ssml/EmphasisLevel.cs#L8

**Comment by timheuer** [comment]
Thanks for the bug report! @all-contributors please add @FelipeBergmann for bug
