### ISSUE TITLE
Signature Validation

### ISSUE THREAD

**Issue by duglah** [timheuer/alexa-skills-dotnet#34]
How do you do the signature validation?
I'm struggling with validation of the signature, see [StackOverflow](https://stackoverflow.com/questions/44892713/alexa-skill-signature-validation-failing) or [Amazon Alexa Forum](https://forums.developer.amazon.com/questions/77731/dotnet-core-10-c-signature-validation.html).

I also tried [X509Certificate2.GetRSAPublicKey()](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions.getrsapublickey(v=vs.110).aspx), but the decrypt and other [functions](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsa_methods(v=vs.110).aspx) are crashing dotnet.

I would like to write a pr, when it's finished, so other devs could use your framework even more easier.

**Comment by stoiveyp** [comment]
If you take a look at the RequestVerification.Verify method I've created within the mentioned PR, I think this should allow you to verify the requests.

I did write unit tests to ensure my test skill worked with the methods but couldn't include them as they included my skill data. I've kept all the individual methods public in case you only need the signature verification piece and not the whole process.
