### ISSUE TITLE
shouldEndSession flag is not allowed with LauchVideoApp.Launch

### ISSUE THREAD

**Issue by DanBusc** [timheuer/alexa-skills-dotnet#41]
Hey,

on my FireTV Stick (Germany) it throws an error if I use the new VideoAppDirective.

Sample:
```
private IDirective getVideoPlayerDirective(SkillRequest input, string song)
        {
            VideoAppDirective dir = new VideoAppDirective();
            VideoItem item = new VideoItem(song);
            VideoItemMetadata meta = new VideoItemMetadata();
            meta.Title = "Testvideo";

            item.Metadata = meta;
            dir.VideoItem = item;

            return dir;
        }

private IDirective GetPlayerDirective(SkillRequest input, string song)
        {

            foreach (var interf in input.Context.System.Device.SupportedInterfaces)
            {
                switch (interf.Key)
                {
                    case "AudioPlayer":
                        return getAudioplayerDirective(input, song);
                    case "VideoApp":
                        return getVideoPlayerDirective(input, song);
                    default:
                        break;
                }
            }
            return null;
        }

     private void SetShouldEndSession(ref SkillResponse response, SkillRequest input, bool endsession)
        {
            foreach (var interf in input.Context.System.Device.SupportedInterfaces)
            {
                if (interf.Key == "AudioPlayer")
                    response.Response.ShouldEndSession = endsession;
            }

        }
public SkillResponse FunctionHandler(SkillRequest input, ILambdaContext context)
        {

            SkillResponse response = new SkillResponse();
            response.Response = new ResponseBody();
            SetShouldEndSession(ref response, input, false);

            IOutputSpeech innerResponse = null;
            var log = context.Logger;

                if (input.GetRequestType() == typeof(LaunchRequest))
                {
//some code
                 }
                 else if (input.GetRequestType() == typeof(IntentRequest))
                {
                    string song = "pathToMP4";

                     var intentRequest = (IntentRequest)input.Request;

                    switch (intentRequest.Intent.Name)
                    {
                        case "AMAZON.YesIntent":
                            log.LogLine($"YesIntent sent: start music " + song);
                            innerResponse = new SsmlOutputSpeech();
                            (innerResponse as SsmlOutputSpeech).Ssml = resource.OkLetsGo;
                            response.Response.Card = card;
                            SetShouldEndSession(ref response, input, true);
                            response.Response.Directives.Add(GetPlayerDirective(input, song));
                            log.LogLine(response.Response.ShouldEndSession.ToString());
                            break;
                       //more Intents..
                       default:
                            break;
                   }
              }
               response.Response.OutputSpeech = innerResponse;
               response.Version = "1.0";
               return response;
}
```

**Comment by stoiveyp** [comment]
@DanBusc Thanks for sending that over, and the error is pretty clear. It's worth mentioning you're not alone in getting it either:

https://forums.developer.amazon.com/questions/77569/trying-to-show-a-video-clip-on-an-echo-show-gettin.html

This is a case that we need to handle, but making ShouldEndSession nullable could break a lot of existing code for one scenario. Are you able to use the following branch of my fork to see if this fixes the issue? If so I can submit it as a pull request for Tim to review as a non-breaking change.

https://github.com/stoiveyp/alexa-skills-dotnet/tree/VideoAppLaunchSessionFix

Let me know how it goes.

**Comment by timheuer** [comment]
The node addition doesn't seem to set any flags? https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/144

**Comment by timheuer** [comment]
FYI @DanBusc the docs say that FireTV does not support the VideoApp directive https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/videoapp-interface-reference

**Comment by stoiveyp** [comment]
With the node version I thought shouldEndSession is optional by default, with their ask and tell methods setting it explicitly?

**Comment by DanBusc** [comment]
Hi @timheuer, hi @stoiveyp!

is ShouldEndSession now nullable? Or how do I create an answer for the Echo Show to play a video? Is there a sample? Also on Echo Show I got an error :(

**Comment by DanBusc** [comment]
@timheuer @stoiveyp any news on this?
I'm currently on V1.4 but error still exists... 

Invalid Directive 
Request Identifier: amz1......
shouldEndSession flag is not allowed with LauchVideoApp.Launch directive

Pls help! 
thx

**Comment by stoiveyp** [comment]
Hey @DanBusc - I've had to add null session handling for the Gadgets API. 

*  Upgrade to 1.4.1
*  Get your response from ResponseBuilder or create it manually.
*  Null out ShouldEndSession before returning it.

See if that works and let us know?

**Comment by DanBusc** [comment]
Cool it’s working... Thx!
Merry christmas!

**Comment by jaddie** [comment]
Looks like another one that can be closed? :)
