### ISSUE TITLE
Missing <speak> SSML from readme

### ISSUE THREAD

**Issue by danclarke** [timheuer/alexa-skills-dotnet#42]
The readme has SSML output as plain text with the occasional bit of extra markup. This will work fine with the simulator, but it won't work with real Echo devices. You need to wrap the entire SSML in <speak> tags. For example:

`<speak>Hello, this works</speak>`
This works

and

`Hello, this only works in the simulator`
This does not

**Comment by timheuer** [comment]
Hmm, good catch, but I swear I used to wrap all Ssml in a <speak> prior.  @stoiveyp do you remember a version where that worked and I wonder if some of the Ssml helpers removed that?  I know if you use those methods and ToXml them that it will add the <speak> wrapper.

**Comment by stoiveyp** [comment]
I double checked the Ssml pull request I submitted to be sure, but the work I did for the Ssml object model was purely additive.

Don't recall an extra speak element ever having been an issue with any of the tests - but probably not a scenario I ever tried to support. Glad it's a quick fix either way.

**Comment by timheuer** [comment]
Yeah really a good callout for a readme fix, which I did.
