### ISSUE TITLE
Sample project does not load in VS 2015

### ISSUE THREAD

**Issue by otratech** [timheuer/alexa-skills-dotnet#45]
Just tried to download the code and open the solution, but getting this error in VS 2015. Ideas? 

Thanks, Crile

..\Alexa.NET.Tests\Alexa.NET.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by timheuer** [comment]
Correct the csproj files are VS2017
		
		

		Get Outlook for iOS
	




On Sat, Aug 12, 2017 at 8:45 PM +0200, "otratech" <notifications@github.com> wrote:












Just tried to download the code and open the solution, but getting this error in VS 2015. Ideas?


Thanks, Crile


..\Alexa.NET.Tests\Alexa.NET.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the  element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by otratech** [comment]
Aha.
