### ISSUE TITLE
Pulling open pull requests into Alpha

### ISSUE THREAD

**Issue by stoiveyp** [timheuer/alexa-skills-dotnet#46]
We currently have three open pull requests ( #32, #35, #44 ) which adds/enhances functionality for the package. Would it be possible to look at moving these into an Alpha release so that areas such as the Display interface could be more easily explored by users?

(apologies for the double-post, my finger slipped on the return key while I was typing)

**Comment by timheuer** [comment]
Merged a bunch into a 1.2.0-pre (alpha branch).  Please test anyone looking for these features (I've been swamped) - NuGet: https://www.nuget.org/packages/Alexa.NET/1.2.0-pre
