### ISSUE TITLE
The response is invalid

### ISSUE THREAD

**Issue by mtavira** [timheuer/alexa-skills-dotnet#48]
I keep getting this error when I test from Alexa: The response is invalid

I deploy the lambda function and works fine with the test functionality on AWS.
When I plug it to custom skill in Alexa, I always get the error "The response is invalid"
I look at the logs of the lambda function and the request is received correctly, the input parameters are identified and the processing is correct.

I wonder if the response format is not what it's expected. Have you had any issue like this?

Any help would be welcome!

**Comment by stoiveyp** [comment]
Hi @mtavira - More than happy to have a look with you, We've seen before that sometimes a skill will get different information in the request depending on what's calling it.

Are you able to use CloudWatch to get your response out of the Lambda so we can see what might be the problem?

**Comment by mtavira** [comment]
Oh, ignore me it was a classic PEBCAK. I shall take another coffee. It works now. Thanks :)
