### ISSUE TITLE
Session end abstracted away?

### ISSUE THREAD

**Issue by BenTMatthews** [timheuer/alexa-skills-dotnet#5]
After digging through the project, which I appreciate a lot, it seems that session end was abstracted away from the ResponseBuilder and set to true in all of the private functions. Was this on purpose for some reason? New to coding on Alexa, but this seems like something that should be available to the public functions.

**Comment by timheuer** [comment]
Good observation @bmatthews99 -- the ResponseBuilder is intended to be the simple helper method.  A "tell" is a fire/forget thing and thus the session end is assumed to be True.  Contradict that to an "ask" response where there also might be a reprompt, but at a minimum you are expecting a second request from the user...this will automatically keep the session alive.

There is no reason, though that an overload couldn't have that specific property exposed, but in creating the helper method for simplicity, the intent was to only have to set the minimum needed to create the response.  Creating up a full SkillResponse is still possible and you can set all the attributes of the response individually.

**Comment by jaddie** [comment]
This issue looks done :+1:
