### ISSUE TITLE
PlaybackFinished returns PlaybackStarted

### ISSUE THREAD

**Issue by vinaykapadia** [timheuer/alexa-skills-dotnet#51]
In Request/Type/AudioPlayerRequest.cs there it shows:

    case "PlaybackStarted":
        return AudioRequestType.PlaybackStarted;
    case "PlaybackFinished":
        return AudioRequestType.PlaybackStarted;

Shouldn't the `PlaybackFinished` case return `AudioRequestType.PlaybackFinished` instead?

**Comment by timheuer** [comment]
Doh!  Good catch, thanks for reporting!

**Comment by vinaykapadia** [comment]
Cool, I'll fix it. Was wondering if that was deliberate or an actual issue. Thanks!

**Comment by jaddie** [comment]
This item has been fixed? Needs closing :)
