### ISSUE TITLE
.Net Framework 4.5 version

### ISSUE THREAD

**Issue by a-stankevich** [timheuer/alexa-skills-dotnet#53]
First, thank you very much for your efforts in implementing and maintaining this library.
It would be great if there also was a version for old school .Net Framework.

I found this can easily be achieved by replacing
`
    <TargetFramework>netstandard1.6</TargetFramework>
`
with
`
    <TargetFrameworks>netstandard1.6;net45</TargetFrameworks>
`
in `Alexa.NET.csproj`. Turns out both versions get built and packed in `.nupkg` without any additional changes.

In fact, I'll go and submit a PR for this.

**Comment by jaddie** [comment]
This might as well be closed since #54 worked out the reasons against this and such etc.

**Comment by timheuer** [comment]
Yes, and the .NET Standard lib should still support NetFx 4.6.1.  

@all-contributors please add @jaddie for bugs
