### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by petersantiago** [timheuer/alexa-skills-dotnet#56]
Does anyone have a complete sample project using this library with a C# Web API project?

Cheers!

Peter

**Comment by consciouspnm** [comment]
or at least a full set of documents to relate it to the Amazon examples?

**Comment by chmasi** [comment]
Would love to have this as well

**Comment by stoiveyp** [comment]
There are some simple examples at https://github.com/stoiveyp/Alexa.NET.Samples - I haven't looked at them for quite a while but the basics should still be good.

Looks like https://github.com/stoiveyp/Alexa.NET.Samples/tree/master/AlexaSamplePetMatch was the most complicated?

Might be of help anyway

**Comment by chmasi** [comment]
Thank you

Freundliche Grüsse
Martin Sickel
______________________________________________

Oberdorfstr. 28
78337 Öhningen
+49 7735 3551
martin@die-sickels.de


Am Fr., 3. Mai 2019 um 16:32 Uhr schrieb Steven Pears <
notifications@github.com>:
