### ISSUE TITLE
Progressive Response

### ISSUE THREAD

**Issue by bauchschuss** [timheuer/alexa-skills-dotnet#57]
Hi,

are there any plans to support "Progressive Response" in your library?

br
martin

**Comment by stoiveyp** [comment]
Morning @bauchschuss. Unfortunately the announcement was made late in the evening my time, so I only saw it this morning - but I'm super excited about it and should be supporting it soon.

**Comment by stoiveyp** [comment]
@bauchschuss Just managed to find time to create a test skill based on #58 and it worked really well :smile: 

Added an IsSupported helper method to the object as currently the test screen in the Alexa dashboard doesn't honor the required properties, so any progressive response work should be wrapped in a check so it doesn't cause the whole skill to fail.
