### ISSUE TITLE
Making Alexa.NET multi language compatible

### ISSUE THREAD

**Issue by TechPreacher** [timheuer/alexa-skills-dotnet#6]
Hi,

if you add the JsonProperty("locale") to Request.cs, Alexa.NET will instantly become multi-language compatible:

```
    public abstract class Request
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("requestId")]
        public string RequestId { get; set; }

        [JsonProperty("locale")]
        public string Locale { get; set; }

        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; }
    }
```

I thought it might be easier this way than going though a pull request... etc. Let me know if you want me to do it.

**Comment by timheuer** [comment]
Thanks for the issue @TechPreacher - you should definitely submit a PR and we'll merge it in!

**Comment by TechPreacher** [comment]
OK, I never did that. I hope your project won't blow up!!! :)

**Comment by timheuer** [comment]
You can quite easily do it via the web interface actually.  You can 'edit'
the file and it should create a PR request based on that edit.


-------
http://timheuer.com/blog/
twitter: @timheuer

**Comment by TechPreacher** [comment]
Done! :)
https://github.com/timheuer/alexa-skills-dotnet/pull/7
