### ISSUE TITLE
Could not find the LambdaSerializerAttribute

### ISSUE THREAD

**Issue by rabejens** [timheuer/alexa-skills-dotnet#61]
I built a basic skill with the help of the examples, but I get the error:

```
Could not find the LambdaSerializerAttribute on the assembly 'NetTestSkill, Culture=neutral, 
PublicKeyToken=null' or method 'TestSkill' while attempting to deserialize input data of type 
'Alexa.NET.Request.SkillRequest'. To use types other than System.IO.Stream as input/output 
parameters, the assembly or Lambda function should be annotated with 
Amazon.Lambda.LambdaSerializerAttribute.: LambdaException
```

What am I missing?

**Comment by rabejens** [comment]
After some googling, I found out I missed the following:

```fsharp
[<LambdaSerializer(typeof<Amazon.Lambda.Serialization.Json.JsonSerializer>)>]
```

Or, in C#:

```csharp
LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))
```
 and the dependency on `Amazon.Lambda.Serialization.Json`

**Comment by JwanKhalaf** [comment]
Where do you put that? I'm getting the same error.

**Comment by stoiveyp** [comment]
You put that between the using statements and your namespace:

```csharp
using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace MySkill
```

This is generated for you if you use the VS AWS Extension and create an AWS Lambda Project, or if you use the dotnet CLI tooling to create a lambda project (docs can be found here https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html  )

Hope this helps

**Comment by JwanKhalaf** [comment]
Thanks, that did it :)

**Comment by sanjeevSOPRA** [comment]
use this if you are using  core 3.1 framework.

using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

**Comment by stoiveyp** [comment]
@sanjeevSOPRA because of the way type is determined within the JSON - there's a lot of logic built around using Newtonsoft within the current version of the assembly and its extensions.

Regardless of .NET framework version, you have to use the JsonSerializer with Alexa.NET or the skill will start to throw exceptions when it tries to successfully deserialize the object model.
