### ISSUE TITLE
How to redirect to another intent?

### ISSUE THREAD

**Issue by rabejens** [timheuer/alexa-skills-dotnet#66]
My skill asks the user at some point if he wants to do additional things with the information he gave. Sometimes, additional slots need to be elicited for this. I am using the dialog API, so I thought I just slap together a new `Intent` with the appropriate state and slots filled, and use a `DialogDelegate`. But when I do this, it goes through without any errors, but my Echo tells me that a problem occurred with my skill.

Is this possible with Alexa.net, and if yes, how?

**Comment by stoiveyp** [comment]
Hi @rabejens, this is definitely possible with Alexa.Net and I'm happy to help figure it out.

Couple of things I'd like to check before we get into specifics.

First of all, does your code keep sending back a DialogDelegate until all the slots are filled?

Your skill will receive an intent request after a DialogDelegate response has asked for the next empty slot. Your skill will need to check each time if there are still slots to fill, and send another DialogDelegate if there are any missing. This loop needs to continue until all the slots are filled in.

If you already have this loop, is your skill sending back an updated intent with the DialogDelegate? Although optional, without the updated intent object in the response, Alexa won't keep track of any updated slots and the skill ends up with previously answered questions being returned as empty next time around.

Let me know about these two areas and if everything checks out we can get into some specifics.

**Comment by rabejens** [comment]
I already accounted for the slot filling for one intent and it works. I'll describe what I have so far and where I am stuck:

- I ask my skill: "Put foo in bar"
- The skill receives the `RelationshipIntent` with both slots `thing` and `parent` filled with `foo` and `bar` respectively
  - If I ask something like "Manage a relationship" it receives the intent with both slots empty, so it sends `DialogDelegate`s and asks the user until both slots are filled.
- It queries a DynamoDB table if `foo` and `bar` both exist
  - If they exist, it puts the relationship in and answers: `bar is now the parent of foo`.
  - If one or both don't exist, it puts three commands onto a list in the session (Create `foo`, create `bar`, make `bar` a parent of `foo`)
  - Then, it says something like `foo and bar do not exist. Do you want me to create them?`
  - If I answer "yes", it goes into the `YesIntent`, gets the first command from the list (which is "Create `foo`" in this example)
  - Now, I want to forge a `NewThing` intent with the `thing` slot filled accordingly, and delegate to it, as if I asked the skill "Create foo"

And at this point I am stuck. I even created a simple skill which has the intents `Foo` and `Bar`, and if I say `Foo` it should redirect to the `Bar` intent, but my Echo still answers with "There was a problem with the skill". When I test it in the Alexa management console, I *do* get a JSON object back that looks like it is the correct `Bar` skill.

Here is what I do (it is F# code with some shortcuts thrown in, but I verified that they work as intended):

```fsharp
            let intent = new Intent()
            intent.Slots <- new Dictionary<string, Slot>()
            let slots = intent.Slots
            match nextTask with
            | NewThing thing ->
                intent.Name <- "NewThing"
                let slot = new Slot()
                slot.Name <- "thing"
                slot.Value <- thing
                slots.Add("thing", slot)
            | // others
            let attribs = session
                          |> attribs
                          |> Map.remove "yes" // This was the list of new commands that got in here on the "yes"
                          // pendingTasks is just a list of tasks to fulfill later. box puts them into a System.Object
                          // so I can serialize them with JSON.net
                          // I am doing this explicitly because deserializing does not always discover the correct
                          // object I want to have
                          |> Map.add "pending" (pendingTasks |> box |> JsonConvert.SerializeObject |> box)
            session.Attributes <- new Dictionary<string, obj>(attribs |> Map.toSeq |> dict)
            ResponseBuilder.DialogDelegate(session, intent)
```

So, what am I missing here?

**Comment by stoiveyp** [comment]
Apologies for misunderstanding @rabejens 

Unfortunately this isn't possible. Nothing to do with the library, it's the behaviour of the Dialog Delegate

Quoting from [Dialog Interface Reference](https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html#delegate)

> Note that you cannot change intents when returning a Dialog directive, so the intent name and set of slots must match the intent sent to your skill.

**Comment by rabejens** [comment]
Ah OK. It's a silly decision, but maybe they have their reason for that - think potential misuses. Then, I'll have to design my conversation a bit differently. I'm closing this issue as the question is answered and it doesn't apply to Alexa.NET but it is Amazon's design decision.
