### ISSUE TITLE
Add support for accessing shopping/todo lists

### ISSUE THREAD

**Issue by timheuer** [timheuer/alexa-skills-dotnet#67]
Should add support (probably a separate NuGet package) for accessing shopping and todo lists: 
https://developer.amazon.com/docs/custom-skills/access-the-alexa-shopping-and-to-do-lists.html

**Comment by stoiveyp** [comment]
List Support is now available as a separate package in #71

**Comment by stoiveyp** [comment]
I've just published [this new package](https://www.nuget.org/packages/Alexa.NET.ListManagement/1.0.0) which gives list management access
