### ISSUE TITLE
Documentation & certificate checking

### ISSUE THREAD

**Issue by consciouspnm** [timheuer/alexa-skills-dotnet#74]
Are there any more examples apart from those in the read.me, for example, does it handle the certificate checking needed if you host your own web service?

**Comment by stoiveyp** [comment]
Alexa.NET does handle the certificate checking through the RequestVerification class. 

This has been turned into MiddleWare with the [Alexa.NET.Security Package](https://github.com/ThomasPe/Alexa.NET.Security)

**Comment by Genfood** [comment]
It would be nice to see a more advanced documentation for this great project.

**Comment by timheuer** [comment]
@Genfood I agree.  I've just had to prioritize my non-work time :-(

**Comment by epsilon-rmroch** [comment]
@stoiveyp 
I saw that you have updated the RequestVerification class.  I have to use my own certificate validation can you add to the documentation an example how to do that?

**Comment by stoiveyp** [comment]
@epsilon-rmroch I can certainly look at updating the docs properly sometime soon, but short term there's an example of how to use the updated `RequestVerification.Verify` method in PR https://github.com/timheuer/alexa-skills-dotnet/pull/191
