### ISSUE TITLE
Is there a sample for sending ProgressiveResponse?

### ISSUE THREAD

**Issue by nishantpant** [timheuer/alexa-skills-dotnet#75]
Is there a sample for sending ProgressiveResponse?

**Comment by stoiveyp** [comment]
Here's a really simple example that will hopefully help. Let me know.

[Alexa.NET.Samples - Progressive Response](https://github.com/stoiveyp/Alexa.NET.Samples/tree/master/ProgressiveResponse)

**Comment by nishantpant** [comment]
Thanks so much for your response. Why doesn't the SendSpeech accept an SSML like everywhere else. It is very cumbersome to handcraft SSML by adding individual elements like this. 

```
				var ssmlOutput = new Speech();
				ssmlOutput.Elements.Add(...);
				if (directive.CanSend())
				{
					await directive.SendSpeech(ssmlOutput);
				}
```

It is way easier to write it like this where I can cram all the SSML into a string. Is there a way to do this in the example above.

```
                    var ssmlOutput = new SsmlOutputSpeech
                    {
                        Ssml = $"<speak>Your address is <say-as interpret-as=\"address\"> {address.StreetNumber} {address.Street}</say-as></speak>"
                    };

```

**Comment by stoiveyp** [comment]
Progressive response is different to sending speech as a regular response, as there's no type requirement. This means you can use the raw SSML if you'd rather and place it into the string version of SendSpeech. It will work as expected.

Here's a link to the relevant documentation. Look a little above where this link sends you, at the "directive.speech" section, for more detailed information about what's acceptable.

[Amazon Alexa - Sending the user a progressive response](https://developer.amazon.com/docs/custom-skills/send-the-user-a-progressive-response.html#directive-response)

**Comment by gotmike** [comment]
seems like this is not able to run asynchronously and send responses while a full response is being built. i am getting a long delay with a stack of responses that include any progressive responses without any delay between them. here is the code i'm using...

```
        // THIS VALUE IS SET BY AlexaMethods.GetLongRunningResponse();
        public static string _LongRunningResult = string.Empty;

        // POST: api/Alexa
        [HttpPost]
        public async Task<OkObjectResult> Post([FromBody] SkillRequest skillRequest)
        {
            var requestType = skillRequest.GetRequestType();

            SkillResponse response = null;

            Task task = AlexaMethods.GetLongRunningResponse();

            if (requestType == typeof(LaunchRequest))
            {
                response = ResponseBuilder.Tell("Hello, Welcome to your skill.");
                response.Response.ShouldEndSession = false;

            }
            if (requestType == typeof(IntentRequest))
            {

                while (_LongRunningResult == string.Empty)
                {

                    var progressive = new ProgressiveResponse(skillRequest);

                    await progressive.SendSpeech("I'm looking up the data, please bear with me.");

                    await Task.Delay(TimeSpan.FromSeconds(2));

                }

                await task;

                response = ResponseBuilder.Tell(_LongRunningResult);
                response.Response.ShouldEndSession = false;
            }
            return new OkObjectResult(response);
        }
```

**Comment by stoiveyp** [comment]
Hi @gotmike - can I ask where you're testing this? Tried async/await code with Progressive Response this morning and it works as expected, but you have to test on a device - the developer console doesn't support progressive response and will just queue the responses and return once.

On a seperate note I see you've a pattern of `ResponseBuilder.Tell` then a second line altering the `ShouldEndSession` property. If you use `ResponseBuilder.Ask` you can clean up those second lines.

Hope this helps
