### ISSUE TITLE
Session problems

### ISSUE THREAD

**Issue by shannonlowder** [timheuer/alexa-skills-dotnet#80]
I'm struggling to pass session data through my skill. My skill is a basic company receptionist. You can "tell the company receptionist Homer Simpson is here to see Montgomery Burns."  When the user passes both intent slots {Employee} and {Visitor} everything works. 

The problem is I want to allow users to be prompted for additional information if they forget one of the slots. Below is the intent slots JSON. again, if both slots are populated, no problem.
` "intent": {
      "name": "VisitorArrived",
      "slots": {
        "Employee": {
          "name": "Employee",
          "value": "Monty burns"
        },
        "Visitor": {
          "name": "Visitor",
          "value": null
        }
      }
    }`

in my skill, I'm using Alexa.NET 1.4.2 (latest per nuget).  In my code that handles the "VisitorArrived" intent I have the following code trying to look in the request first, and session second for the two slots' data.

`//try to get the Employee from the request
                        try {
                            if (intentRequest.Intent.Slots["Employee"].Value.Length > 0) {
                                employee = intentRequest.Intent.Slots["Employee"].Value;
                                skillResponse.SessionAttributes["Employee"] = employee;
                            }
                        } catch {
                            log.LogLine("Employee wasn't included in the request.");
                            //try to get Employee from the session
                            try {
                                if (input.Session.Attributes["Employee"].ToString().Length > 0)
                                    employee = input.Session.Attributes["Employee"].ToString();
                            } catch {
                                log.LogLine("Employee wasn't included in the session.");
                            }
                        }
                        //try to get the Visitor from the request
                        try {
                            if (intentRequest.Intent.Slots["Visitor"].Value.Length > 0) {
                                visitor = intentRequest.Intent.Slots["Visitor"].Value;
                                skillResponse.SessionAttributes["Visitor"] = visitor;
                            }
                        } catch {
                            log.LogLine("Visitor wasn't included in the request.");
                            //try to get Visitor from the session
                            try {
                                if(input.Session.Attributes["Visitor"].ToString().Length > 0)
                                    visitor = input.Session.Attributes["Visitor"].ToString();
                            } catch {
                                log.LogLine("Visitor wasn't included in the session.");
                            }
                        }

                        log.LogLine("Employee: " + employee);
                        log.LogLine("Visitor: " + visitor);`

It never seems to save the data to the session, or pull it from the session on the next request.  I feel like I'm missing something simple.  Any advice would be greatly appreciated!

**Comment by stoiveyp** [comment]
Hi @shannonlowder - apologies if I'm asking an obvious question. The response SessionAttributes is a dictionary object - so I would expect the employee and visitor keys to be added somewhere, is there a SessionAttributes.Add earlier on in the function?

As an aside when you're maintaining state you might find it easier to only use one session object. If you grab the session from the request at the beginning of your function - use that throughout the function - and then set the response session to the same object on output, then you're not having to try and transfer settings/values between the two; I find it makes session maintenance easier.

**Comment by ElvenMonky** [comment]
Do you also set ShouldEndSession to false?

**Comment by shannonlowder** [comment]
Sorry for the delay... I've been stuck on other projects. I'll try to get back on to this tonight., I'll revise this reply then.  Thanks, guys!

**Comment by senpAi95** [comment]
Hi,
I am trying to save the session details. If I have to switch the intent from one intent to other intent based on session attributes, How can i change the slot type for dialog delegation to match to the switched intent?

Ex:
intent_name = pinintent {slot name = pin}
 
now based on the session attributes i have to change the intent name, say Inquiry
intent_name = inquiryintent {slot name = inquiry slot}

If i have to use dialog delegate, i have to change slot "pin" to "inquiry slot" and name to 'intent_name' to handle the delegation.

Can i change SkillRequest Object after i receive, to process my needs? If so Please let me know the approach?
Like
"slots": {
				"xyz": {
					"name": "xyz",
					"value": "x",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": ,
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "o",
											"id": ""
										}
									}
								]
							}
						]
					},
					"confirmationStatus": "NONE"
				}
			}

to

"slots": {
				"pin": {
					"name": "pin",
					"value": "12",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": ".pin",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "pin",
											"id": "yz"
										}
									}
								]
							}
						]
					},
					"confirmationStatus": "NONE"
				}
			}

in request object based on session attributes..

Hope I made sense in this comment.
Thanks

**Comment by stoiveyp** [comment]
Hi @senpAi95 - I'm afraid you're not able to change the intent of a request, what will happen is that you'll send the updated intent in the response and that will most likely generate a System.ExceptionEncountered request.

I'd suggest looking at adding the slots from the second intent into the list of the first, don't change any of your phrases in the first intent, then use dialog management to ask for the values where appropriate.

Happy for you to open a new issue and put the details in - then I can help you with the detail.
