### ISSUE TITLE
Asking for additional infos

### ISSUE THREAD

**Issue by janniksam** [timheuer/alexa-skills-dotnet#81]
I have a design problem and I don't know how to solve them yet.
These two questions are done by the Dialog Model and work pretty good so far:

**Me:** Alexa, tell Fruit Vendor I want to buy fruits?
**Alexa:** Which city are you in?
**Me:** Amsterdam
**Alexa:** When do you want to come to get them?
**Me:** Tommorow.

With this information I can query my DB and get back some fruits.
After that I would like give the user a choice between those fruits from my DB?

**Alexa:** We have a selection in stock. 1. Apples, 2. Tomatoes, 3. Bananas. Select the number of the fruit you want to buy?
**Me:** Number 1.
**Alexa:** How much apples you would like to buy?
**Me:** Two
**Alexa:** Okay, I reserved two Apples for you.

How can I do that? I would like to avoid multiple intends, if this is even possible in a single one.
Is there something like a Ellicit with a custom prompt?

**Comment by stoiveyp** [comment]
This feels like a situation with lots of possible ways of keeping the order going by giving specific output (out of stock but we have these alternatives, fruit available but another day etc. ), so multiple intents might be easier.

That said - you could make a single intent which is "I want to buy {numberOfFruit} {fruit} in {city} {pickupDate}" and then use the dialog model to fill in the blanks.

You wouldn't be able to do "number 1" etc. for the fruit kinds, but to do that would require each conversation have a known list so you'd have to create multiple intents at that stage.

**Comment by janniksam** [comment]
Thanks for the quick response.

The real usecase wouldn't be "Fruits", it was just to make the example a bit more clear. :)

To be a bit more specific:
I choose a city and in each city I have up to five special places I would like to choose from.
Those 5 places can be anything, it's just a dynamic string which I have no influence on.

So in order to get to know those places I first have the user select the city, so I can limit all the place opportunitys to a maximum of five places. So, a known list is not possible, cause it is very dynamic.

I hope you understand what I mean.

**Comment by stoiveyp** [comment]
That makes sense, thank you.

If you were sure you only wanted one intent? You could create a slot for the numbered results, and not include it in the intent phrases. Then - when a phrase with the city was used, you could build a response with the list data and use the ElicitSlot directive to specifically ask the user for one of the given numbers.

Would that work for you?

**Comment by janniksam** [comment]
Hello Steven,

thanks. 

I don't like to use two  intents,  because it's very unnatural for me to have to say  a whole sentence instead of just a number,  so the second intend is called,  after I told alexa my city and date. Further more there's the risk,  that the second intent Is called before the first one,  isn't it? I don't know,  I just started learning to build skills, and I find to have a good design is very important.  :) 

Anyways,  you told me to build a "response with the 
list data and  use the elicit directive" for the numbers,  but I'm not sure you mean by that.  
If you have 5 minutes I'd love to see a very quick  example. 

Jannik
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 13.02.18, 21:19, Steven Pears <notifications@github.com> schrieb:
That makes sense, thank you.
If you were sure you only wanted one intent? You could create a slot for the numbered results, and not include it in the intent phrases. Then - when a phrase with the city was used, you could build a response with the list data and use the ElicitSlot directive to specifically ask the user for one of the given numbers.
Would that work for you?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timheuer/alexa-skills-dotnet","title":"timheuer/alexa-skills-dotnet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timheuer/alexa-skills-dotnet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stoiveyp in #81: That makes sense, thank you.\r\n\r\nIf you were sure you only wanted one intent? You could create a slot for the numbered results, and not include it in the intent phrases. Then - when a phrase with the city was used, you could build a response with the list data and use the ElicitSlot directive to specifically ask the user for one of the given numbers.\r\n\r\nWould that work for you?"}],"action":{"name":"View Issue","url":"https://github.com/timheuer/alexa-skills-dotnet/issues/81#issuecomment-365391492"}}}
