### ISSUE TITLE
Any samples for Echo Show/Spot templates.

### ISSUE THREAD

**Issue by nishantpant** [timheuer/alexa-skills-dotnet#84]
First of all. Amazing job with this package. Many many thanks to the entire team.

Question: Are there any samples for Echo show/Spot templates? like lists etc

**Comment by JonRoperuk** [comment]
Did you manage to get a response on this?  I'm trying this and i need to know how to apply a bodytemplate

**Comment by stoiveyp** [comment]
I wrote some inline code with https://github.com/timheuer/alexa-skills-dotnet/issues/55 that should give you an idea of how templates can be returned as part of your response.
