### ISSUE TITLE
Always get Forbidden when trying to get address

### ISSUE THREAD

**Issue by yogiderek** [timheuer/alexa-skills-dotnet#85]
I am always getting the Forbidden status returned when i try to the get the users  full address. I have checked that permission has been granted via the Alexa app and I can see the blue tick against device address and my address has been entered.

Here is my code, am i misusing the api?

```
if (request.GetRequestType() == typeof(LaunchRequest))
{
	string apiAccessToken = request.Context.System.ApiAccessToken;
	string deviceId = request.Context.System.Device.DeviceID;
	string apiEndpoint = request.Context.System.ApiEndpoint;
	AddressResponse address = null;
	HttpStatusCode statusCode = DeviceAddressService.GetAddress(apiEndpoint, deviceId, apiAccessToken, out address);

	// 

}


public static HttpStatusCode GetAddress(string apiEndpoint, string deviceId, string apiAccessToken, out AddressResponse response)
{
	string uri = $"{apiEndpoint}/v1/devices/{deviceId}/settings/address";
	RestClient client = new RestClient(uri);
	RestRequest request = new RestRequest { RequestFormat = DataFormat.Json };
	request.AddHeader("Authorization", "Bearer " + apiAccessToken);

	IRestResponse<AddressResponse> addressResponse = client.Execute<AddressResponse>(request);
	response = addressResponse.Data;

	if (addressResponse.StatusCode == HttpStatusCode.Forbidden)
	{
		// permission to access address has not been granted
		return HttpStatusCode.Forbidden;
	}

	return HttpStatusCode.OK;
}

```

**Comment by stoiveyp** [comment]
Initially that looks good. Unless someone else spots something I can't, if you can you retrieve the response body there should hopefully be more information in there as to the exact reason you're not getting through - Amazon are normally pretty good at giving back useful messages.

**Comment by yogiderek** [comment]
Looking at the response in more detail I see that it tells me that the authentication token is not valid. What I do not understand is that the value of the token indicates that permission has been granted or not and since I can see it has been granted in the Alexa app i would expect the token to indicate that.

I have 2 devices connected, one is offline. The one that is online is the one where permission has been granted.

I have attached a screen shot of the response. I apologise if i have wasted your time - should i direct this to Amazon?

![image](https://user-images.githubusercontent.com/2614368/38460802-58fa8a12-3ab9-11e8-9f92-5ab2c0568c73.png)

**Comment by yogiderek** [comment]
I think i have found the problem. 

I said that i had 2 devices

F1234 Echo      Offline (work) no address entered and not sure if authorisation granted or not
F1234 Echo Dot  Online  (home) address entered and authorisation granted

I checked the work device and it's address was not set up. I did 2 things here. First was to set the address and second was to rename the Echo Dot to Dereks Echo Dot. So I think the Alexa app may look down the list of devices which is in alphabetical order, find that the first device does not have its address set and just fails. I am not sure if this is a known problem but i will check later and report it to Amazon if not.

When I made the changes above, everything worked perfectly.

Thanks for a great library. Now I just need to understand the best place to put the code to verify the authenticity of the request.

**Comment by raymondjstone** [comment]
For me at least (I have about 10 alexa devices) the address permission on my skill is one value for all devices. What I do find however is that the alexa app seems to have my live skill while the alexa website has the dev skill and so I need to stick to setting permission on the website only, but I need to do that anyway since the alexa app does not currently have notification permissions here
