### ISSUE TITLE
Appveyor isn't running tests

### ISSUE THREAD

**Issue by stoiveyp** [timheuer/alexa-skills-dotnet#87]
There are ~70 tests in Alexa.NET.Tests, but they're not run on generation of a PR request, so a breaking change might be missed.

By changing the value of the Appveyor test section to Script, and the parameters to CMD you can then run:

`dotnet test .\Alexa.NET.Tests`

which should negate this risk

**Comment by stoiveyp** [comment]
Ahh sorry - I just generated #86 and appveyor is still running as a PR check, my bad

**Comment by timheuer** [comment]
I still have it running as I was building confidence in VSTS :-) -- however that is fully running, executing tests and deploying to nuget now as well.  https://timheuer.visualstudio.com/Alexa.NET/_build/index?buildId=21&_a=summary

**Comment by stoiveyp** [comment]
Ahh okay. Can I ask what the motivation was? Got a lot of appveyor builds - wondering if it's worth moving them over in time.

**Comment by timheuer** [comment]
Yeah, good question!  I loved AppVeyor, however I started having issues with NuGet support there and being a MSFT employee I wanted to better learn VSTS (since my office mates help build it :-)).  I'm only using VSTS build and it allowed me a more familiar flow for dotnet cli plus other extensions.  I've liked the config more with VSTS since moving over.

**Comment by adriangodong** [comment]
I ❤️  both VSTS and AppVeyor.

My primary reason to avoid VSTS is because I ran out of build credit and I want to avoid getting spam PRs and have to pay for those PRs to build. :D

@timheuer please make sure the builds are publicly accessible. I'm getting 404 / unauthorized error on the link above.

**Comment by timheuer** [comment]
@adriangodong - i just realized that VSTS doesn't allow public build logs.  The badge on the front is the 'public' visibility of success/fail.  I'm looking into this but right now as I understand VSTS public builds is not a capability.  #sadface
