### ISSUE TITLE
NuGet package not working with VS2017

### ISSUE THREAD

**Issue by timheuer** [timheuer/alexa-skills-dotnet#9]
Can't install NuGet package.

**Comment by matthiasxc** [comment]
I'm not having a problem with VS2017 Community (15.0.0-RTW+26228.4).
For what it's worth:
.NET 4.6.01586
NuGet Package Manager 4.0.0

**Comment by timheuer** [comment]
I'm not either -- this was reported by a user on Twitter.  I couldn't repro the scenario as he was able to use the AWS Lambda plugin within VS2017 that I couldn't even get to work :-).  Closing this as not reproducible for now.
