### ISSUE TITLE
I cant get slot information

### ISSUE THREAD

**Issue by foojr** [timheuer/alexa-skills-dotnet#90]
I cant get slot information using something like this. 
var firstValue = intentRequest.Intent.Slots["FirstSlot"].Value;
seems pretty simple. Slot is created on the right intent and I am inside the right intent already.
Any ideas?

**Comment by foojr** [comment]
gives me an error on the line before, no matter what I have there
{
  "errorType": "NullReferenceException",
  "errorMessage": "Object reference not set to an instance of an object.",
  "stackTrace": [
    "at Pillar.Function.FunctionHandler(SkillRequest input, ILambdaContext context) in C:\\Users\\.....\Function.cs:line 87,
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ]
}

**Comment by foojr** [comment]
I got it, just forgot to rebuild the model.

**Comment by raymondjstone** [comment]
foojr you have not closed the issue
