### ISSUE TITLE
Support for canFillIntentRequest?

### ISSUE THREAD

**Issue by nishantpant** [timheuer/alexa-skills-dotnet#95]
Any plans for adding support for CanFillIntentRequest?

https://developer.amazon.com/docs/custom-skills/understand-name-free-interaction-for-custom-skills.html

**Comment by stoiveyp** [comment]
Hi @nishantpant - that functionality was added as part of the [latest pre-release](https://www.nuget.org/packages/Alexa.NET/1.5.5-pre)

**Comment by nishantpant** [comment]
Very cool. You guys have done such an amazing job with this. By any chance is there a sample code snippet somewhere, you could share?

**Comment by stoiveyp** [comment]
I don't have a sample, but there's some snippets in [my recent blog article about it](https://www.imacode.ninja/2018/06/09/skill-discovery-canfulfillintentrequest-in-alexa-net/)
