### ISSUE TITLE
switching intents with dialog management

### ISSUE THREAD

**Issue by senpAi95** [timheuer/alexa-skills-dotnet#96]
I have 2 intents x,y. Lets say x has dialog interface. Before even starting the response to that request, I have to check for a condition which is fulfilled by intent y. If its false, Alexa has to ask the user and after its true, dialog interface should match for intent x. 
The scenario is almost like a having a PIN before using your skill. 
Its easy when there is no dialog interface with the intent, but that's what making it challenging. Any sort of help is appreciated. Thanks for the prompt response earlier @stoiveyp .

**Comment by senpAi95** [comment]
https://developer.amazon.com/blogs/alexa/post/d8579cd6-9109-42b2-ada6-df017fc1dee5/how-to-handle-different-intent-requests-with-dialog-management

Its similar to this, but I couldn't create similar to that using this awesome deserializing nugget.

**Comment by stoiveyp** [comment]
Hi @senpAi95 - off the back of this issue I'm currently converting the Pet Match sample skill into C#. You can see the progress I made today here:
https://github.com/stoiveyp/Alexa.NET.Samples/tree/master/AlexaSamplePetMatch

Once I've moved the rest across, I'll implement the code from the article you mentioned to show it can work.

**Comment by anandmukundan** [comment]
Amazon just announce dialog chaining as officially supported. 

https://developer.amazon.com/blogs/alexa/post/9ffdbddb-948a-4eff-8408-7e210282ed38/intent-chaining-for-alexa-skill

From what I can see, there needs to no change in the SDK, just returning an updated intent with a different intent name should work.

@stoiveyp or @timheuer comments?

**Comment by stoiveyp** [comment]
Great feature, I agree there's no changes as you can create the directives with the intent object and the chained intent name.

I'll definitely be adapting some skills to use that!
