### ISSUE TITLE
Add Support for In Skill Purchase Request

### ISSUE THREAD

**Issue by dyl10s** [timheuer/alexa-skills-dotnet#97]
Keep getting an error when receiving a Request of type "Connections.Response" :(

**Comment by stoiveyp** [comment]
Hi @dyl10s. This repo is for the core request and responses types, but we've written it in such a way that it can be extended. In-Skill Pricing for Alexa.NET skills can be found [In it's own NuGet Package](https://www.nuget.org/packages/Alexa.NET.InSkillPricing/) and hooks into that extensible mechanism.

The package docs should have enough to get it wired up to an Alexa.NET skill, and please feel free to raise any issues you have [against the repo here](https://github.com/stoiveyp/Alexa.NET.InSkillPricing)

Hope this helps

**Comment by dyl10s** [comment]
Awesome thanks!
