### ISSUE TITLE
Absent token property from Request class

### ISSUE THREAD

**Issue by Maria1222w2** [timheuer/alexa-skills-dotnet#98]
Hello, 
I am building a skill  with Alexa.Net library in which I am using cards.
I am wondering why don't we have in the Request class Token property too?

**Comment by stoiveyp** [comment]
The token you send down as part of a display template is only sent back though a Display.ElementSelected event - so when your skill receives that we create a specific request type that exposes the token for you.

https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/Type/DisplayElementSelectedRequest.cs

Hope this helps get the value you need.

**Comment by Maria1222w2** [comment]
yes, it makes sense.  thank you

**Comment by jaddie** [comment]
This one can be closed? :)
