### ISSUE TITLE
Request class being abstract gives errors when using with Azure Functions

### ISSUE THREAD

**Issue by devedse** [timheuer/alexa-skills-dotnet#99]
One of the members of SkillRequest is named Request. Which is an abstract class. When using this code in Azure Functions, C# can't deserialize the JSON to an abstract class.

My proposal would be to remove the abstract part and make it a normal class.

Error:
```
2018-06-28T14:04:13.298 [Error] System.Private.CoreLib: Exception while executing function: AccountLinking2. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. Newtonsoft.Json: Could not create an instance of type Alexa.NET.Request.Type.Request. Type is an interface or abstract class and cannot be instantiated. Path 'request.type', line 30, position 9.
2018-06-28T14:04:13.416 [Error] Executed 'AccountLinking2' (Failed, Id=a00304f2-5654-4102-b5e0-0cc2f9bd4fa7)
```

Edit:
~~I created a pull request to fix this issue #100 .~~
If you accept this, can you also make sure a new NuGet package will be published?

Edit2:
This pull request probably isn't the right way to solve it.

**Comment by stoiveyp** [comment]
Sorry - that was a silly question, your original error message had Newtonsoft in it, I just didn't scroll enough.

**Comment by stoiveyp** [comment]
Are you able to provide the JSON conversion code you're using in the function to get from the json to the SkillRequest object? Thanks.

**Comment by devedse** [comment]
Well with Azure Functions this all happens behind the scene I assume. So this is basically my code:
```
    public static class Function1
    {
        [FunctionName("Alexa")]
        public static async Task<SkillResponse> Run([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] [FromBody]SkillRequest req, TraceWriter log)
        {
            SkillResponse response = null;
            if (req?.Session?.User?.AccessToken != null)
            {
                ClaimsPrincipal principal = await Security.ValidateTokenAsync(req.Session.User.AccessToken);
                if (principal != null)
                {
                    PlainTextOutputSpeech outputSpeech = new PlainTextOutputSpeech();
                    string firstName = (req.Request as IntentRequest)?.Intent.Slots.FirstOrDefault(s => s.Key == "FirstName").Value?.Value;
                    outputSpeech.Text = "Hello " + firstName;
                    response = ResponseBuilder.Tell(outputSpeech);
                }
            }
            return response;
        }
    }
}
```

I followed the tutorial from Microsoft here:
https://blogs.msdn.microsoft.com/premier_developer/2018/01/25/amazon-alexa-skills-authenticated-by-azure-active-directory-and-backed-by-an-azure-function/

Basically just following all their steps results in the error I described.

**Comment by stoiveyp** [comment]
Hi @devedse - sorry I haven't had chance to look at this until this morning.

I've put a working example here https://github.com/stoiveyp/Alexa.NET.Samples/tree/master/AzureFunction - worth mentioning it didn't work when the skill request object was actually named request, hence it called req

**Comment by devedse** [comment]
@stoiveyp, I'll check out the sample thanks. I indeed also ran into that error and submitted a Github post here:
https://github.com/Azure/azure-functions-host/issues/3071
I'm quite stumped on how that error happens.

**Comment by damienmccauley** [comment]
Hi, I am having the same issue from both my application and when using the sample code you provided @stoiveyp do we have any more information / work arounds?
I was wondering if the json payload from amazon changed to simply be type request as opposed to a concrete type in Alexa.Net?
Are there any plans to change request to a concrete type? (I noticed that this was implemented and then abandoned. )
Any information greatly appreciated.

**Comment by stoiveyp** [comment]
Hi @damienmccauley - the request type is the discriminating value that determines what fields should be available with each request, which is why request remains abstract.

I also got an error trying to re-run my old sample; so this still appears to be an issue with Azure Function bindings not honoring Json.Net custom converters. I've made a small update to the sample function to show that this is the case by manually deserializing the request inside the function - which should output json as expected.

```csharp
 [FunctionName("AlexaNetSample")]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]string req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            var request = JsonConvert.DeserializeObject<SkillRequest>(req);

            if (request.Request is LaunchRequest)
            {
                return new OkObjectResult(ResponseBuilder.Tell("you launched from method param"));
            }

            return new OkObjectResult(ResponseBuilder.Empty());
        }
```

Hope this is a suitable workaround

**Comment by damienmccauley** [comment]
Thanks @stoiveyp, right you are on the AzureFuns bindings.

**Comment by mikelor** [comment]
Hi All,
There was a change in the HttpTrigger signature from version 1.0 to 2.0 of Azure Functions.
The HttpRequest req parameter became HttpRequestMessage req

To work around this, I did the following

`SkillRequest input = await req.Content.ReadAsAsync<SkillRequest>();`

Here's a loose sample...

~~~~ 
      [FunctionName("AlexaSkill)]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            // Get to the content
            SkillRequest input = await req.Content.ReadAsAsync<SkillRequest>();

            string responseMessage = "";

            switch (input.Request)
            {
                case LaunchRequest launch:
                    responseMessage = @"Welcome to the Machine";
                    break;
                case IntentRequest intent:
                    switch (intent.Intent.Name)
                    {
                        case BuiltInIntent.Cancel:
                        case BuiltInIntent.Stop:
                            //blah blah
                            break;
                        default:
                            break;
                    }
                    break;
                default:
                    break;
            }
            return new OkObjectResult(ResponseBuilder.Tell(responseMessage));

        }
~~~~

**Comment by jaddie** [comment]
This one can be closed too? :)
